package main

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// connectorEnrollmentToken is the opaque one-time token the Admin Console's "Add connector" mints for a Site. It
// carries everything a connector needs to reach and enroll into its Site, so a first-run start is just --token
// (plus, in production, the connector's own certificate). Single-use and short-lived: after enrollment it is
// invalid, which is exactly why the connector persists its own state and never needs the token again.
type connectorEnrollmentToken struct {
	V         int    `json:"v"`
	EdgeURL   string `json:"edge_url"`
	TenantID  string `json:"tenant_id"`
	Site      string `json:"site"` // the connector group id the connector enrolls into
	Bootstrap string `json:"bootstrap"`
	Region    string `json:"region"`
	Cluster   string `json:"cluster"`
	EdgeCAPEM string `json:"edge_ca,omitempty"` // the Edge transport CA to pin (public, not a secret)
	// EdgeEndpoints is every door the deployment answers on, "region=URL;region=URL".
	//
	// ★★★ WITHOUT IT A CONNECTOR INSTALLED THE SUPPORTED WAY CANNOT FAIL OVER (2026-08-26). The token carried
	// one edge_url, so a connector built from it had one door — and everything behind it went away with that
	// region until somebody edited its command line. Region failover was implemented and measured with
	// --edge-endpoints passed by hand, which is not a path any customer is given.
	EdgeEndpoints string `json:"edge_endpoints,omitempty"`
	// OrgServerName / OrgEnrolServerName / OrgAnchorsPEM are the organization's OWN door and the authority
	// that signs it. When present they replace edge_ca as what this connector pins, and the name is what it
	// sends in every ClientHello — the addresses it dials are unchanged.
	//
	// ★★★ A CONNECTOR USED TO TAKE THE DEPLOYMENT'S NAME AND ROOT WHATEVER ITS ORGANIZATION HAD (2026-09-07,
	// measured on twenty organizations that each had a door answering in all three regions). Absent still
	// means the deployment's shared certificate, which is correct for an organization with no door of its own
	// and for every token issued before this field existed.
	OrgServerName      string `json:"org_server_name,omitempty"`
	OrgEnrolServerName string `json:"org_enrol_server_name,omitempty"`
	OrgAnchorsPEM      string `json:"org_anchors,omitempty"`
}

// connectorState is what a connector persists after first-run enrollment so every later start reconnects with NO
// token and NO flags. The runtime secret is generated by the connector and its hash is what the Edge remembers
// for heartbeat auth, so a rotation of the Site's bootstrap secret never breaks an already-enrolled connector.
type connectorState struct {
	EdgeURL       string `json:"edge_url"`
	TenantID      string `json:"tenant_id"`
	Site          string `json:"site"`
	ConnectorID   string `json:"connector_id"`
	RuntimeSecret string `json:"runtime_secret"`
	Region        string `json:"region"`
	Cluster       string `json:"cluster"`
	EdgeCAPath    string `json:"edge_ca_path,omitempty"`
	// EdgeEndpoints persists the door list so every later start has it without the token — the same reason
	// every other enrolment fact is persisted here.
	EdgeEndpoints string `json:"edge_endpoints,omitempty"`
	// EdgeServerName is the name this connector sends in the ClientHello, and EdgeEnrolmentServerName the one
	// it sends on the connection that carries a CSR. Empty on a connector whose organization has no door of
	// its own: the dialled host is then the name, exactly as before.
	EdgeServerName          string `json:"edge_server_name,omitempty"`
	EdgeEnrolmentServerName string `json:"edge_enrolment_server_name,omitempty"`
}

func decodeConnectorEnrollmentToken(s string) (connectorEnrollmentToken, error) {
	var tok connectorEnrollmentToken
	s = strings.TrimSpace(s)
	raw, err := base64.RawURLEncoding.DecodeString(s)
	if err != nil {
		if raw, err = base64.StdEncoding.DecodeString(s); err != nil {
			return tok, fmt.Errorf("token is not valid base64: %w", err)
		}
	}
	if err := json.Unmarshal(raw, &tok); err != nil {
		return tok, fmt.Errorf("token payload is not valid: %w", err)
	}
	if strings.TrimSpace(tok.EdgeURL) == "" || strings.TrimSpace(tok.Site) == "" {
		return tok, fmt.Errorf("token is missing edge_url or site")
	}
	return tok, nil
}

func generateConnectorID() string {
	b := make([]byte, 6)
	_, _ = rand.Read(b)
	return "conn-" + hex.EncodeToString(b)
}

func generateConnectorRuntimeSecret() string {
	b := make([]byte, 24)
	_, _ = rand.Read(b)
	return base64.RawURLEncoding.EncodeToString(b)
}

func loadConnectorState(path string) (connectorState, bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return connectorState{}, false, nil
		}
		return connectorState{}, false, err
	}
	var st connectorState
	if err := json.Unmarshal(data, &st); err != nil {
		return connectorState{}, false, fmt.Errorf("connector state %s: %w", path, err)
	}
	return st, true, nil
}

func saveConnectorState(path string, st connectorState) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	data, err := json.MarshalIndent(st, "", "  ")
	if err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func connectorFirstNonEmpty(a, b string) string {
	if strings.TrimSpace(a) != "" {
		return a
	}
	return b
}

// connectorEnrollmentFlags is the subset of connector settings that enrollment resolves — either from a one-time
// token (first run) or from persisted state (every later run). Passed by pointer so resolution overrides them.
type connectorEnrollmentFlags struct {
	EdgeURL, TenantID, Site, ConnectorID, ConnectorSecret, BootstrapSecret, Region, Cluster, EdgeTransportCA *string
	// EdgeEndpoints is filled from the token or the saved state, and left alone when the operator passed one.
	EdgeEndpoints *string
	// EdgeServerName is the organization's own door name, filled from the token or the saved state.
	EdgeServerName *string
}

func (f connectorEnrollmentFlags) apply(st connectorState) {
	*f.EdgeURL = st.EdgeURL
	*f.TenantID = st.TenantID
	*f.Site = st.Site
	*f.ConnectorID = st.ConnectorID
	*f.ConnectorSecret = st.RuntimeSecret
	if st.Region != "" {
		*f.Region = st.Region
	}
	if st.Cluster != "" {
		*f.Cluster = st.Cluster
	}
	if st.EdgeCAPath != "" {
		*f.EdgeTransportCA = st.EdgeCAPath
	}
	if f.EdgeServerName != nil && strings.TrimSpace(*f.EdgeServerName) == "" && st.EdgeServerName != "" {
		*f.EdgeServerName = st.EdgeServerName
	}
	// ★ AN OPERATOR WHO PASSED A LIST KEEPS IT. Theirs is a deliberate choice about which doors this connector
	// may use; the deployment's map is what to use when they have not made one.
	if f.EdgeEndpoints != nil && strings.TrimSpace(*f.EdgeEndpoints) == "" && st.EdgeEndpoints != "" {
		*f.EdgeEndpoints = st.EdgeEndpoints
	}
}

// resolveConnectorEnrollment turns --token (first run) or the saved state (later runs) into the connector's
// effective settings. Returns firstRun=true when a token was consumed. With no state-dir it is a no-op, so the
// legacy explicit flags keep working unchanged.
func resolveConnectorEnrollment(stateDir, token string, f connectorEnrollmentFlags) (bool, error) {
	stateDir = strings.TrimSpace(stateDir)
	if stateDir == "" {
		return false, nil
	}
	statePath := filepath.Join(stateDir, "connector-state.json")

	if strings.TrimSpace(token) != "" {
		tok, err := decodeConnectorEnrollmentToken(token)
		if err != nil {
			return false, err
		}
		// ★★★ THE STATE WINS OVER A TOKEN THAT SAYS THE SAME THING (2026-08-25, measured on the two-region lab
		// while trying to route one flow through a connector).
		//
		// This branch used to run whenever a token was present: it minted a NEW connector id, overwrote the
		// state file, and registered a second connector. The flag's own text says "first run only" and expects
		// the token to be REMOVED afterwards — and nothing an operator actually runs works that way. The
		// Console's "Add connector" hands over one self-contained command; that command becomes a systemd
		// unit, a docker run, a service's arguments, and every one of them passes the same argv on every start.
		//
		// So every restart minted a fresh identity. Measured: one site with one running connector held SEVEN,
		// six of them dead, the registry grew without bound, and a route bound to the connector an operator
		// could see stopped applying the moment that connector restarted — the binding named an id that no
		// longer existed and nothing said so.
		//
		// A token that names the same deployment, site and Edge as the state is the SAME enrolment arriving
		// again, and re-enrolling is not what it asks for. A token naming something DIFFERENT is a deliberate
		// move — that is the one case where the state is replaced, and it says so out loud.
		if st, ok, lerr := loadConnectorState(statePath); lerr == nil && ok && connectorStateMatchesToken(st, tok) {
			f.apply(st)
			return false, nil
		} else if lerr == nil && ok {
			log.Printf("connector: the enrollment token names a different deployment/site than the state in %s "+
				"(state: tenant %q site %q edge %q; token: tenant %q site %q edge %q) — treating this as a "+
				"deliberate move and enrolling again, which leaves the old identity behind",
				stateDir, st.TenantID, st.Site, st.EdgeURL, tok.TenantID, tok.Site, tok.EdgeURL)
		}
		st := connectorState{
			EdgeURL:       tok.EdgeURL,
			TenantID:      tok.TenantID,
			Site:          tok.Site,
			ConnectorID:   generateConnectorID(),
			RuntimeSecret: generateConnectorRuntimeSecret(),
			Region:        connectorFirstNonEmpty(tok.Region, *f.Region),
			Cluster:       connectorFirstNonEmpty(tok.Cluster, *f.Cluster),
			// ★ THE BOOTSTRAP HALF. This is what the FIRST connection needs when the region the token names is
			// the one that is away; the durable list arrives over the tunnel afterwards and replaces it, the
			// same way a device takes its region list from its profile rather than from what it enrolled with.
			EdgeEndpoints: tok.EdgeEndpoints,
		}
		// ★★★ THE ORGANIZATION'S OWN AUTHORITY WINS OVER THE DEPLOYMENT'S, AND BOTH HALVES MOVE TOGETHER.
		// Pinning an organization's CA while sending the deployment's name is served the deployment's
		// certificate and fails verification; sending the organization's name while pinning the deployment's
		// root fails the same way from the other side. So the name and the anchors are taken as a pair, or
		// neither is taken.
		anchors := strings.TrimSpace(tok.EdgeCAPEM)
		if strings.TrimSpace(tok.OrgServerName) != "" && strings.TrimSpace(tok.OrgAnchorsPEM) != "" {
			anchors = strings.TrimSpace(tok.OrgAnchorsPEM)
			st.EdgeServerName = strings.TrimSpace(tok.OrgServerName)
			st.EdgeEnrolmentServerName = strings.TrimSpace(tok.OrgEnrolServerName)
		}
		if anchors != "" {
			if err := os.MkdirAll(stateDir, 0o700); err != nil {
				return false, fmt.Errorf("create state dir: %w", err)
			}
			caPath := filepath.Join(stateDir, "edge-ca.pem")
			if err := os.WriteFile(caPath, []byte(anchors+"\n"), 0o600); err != nil {
				return false, fmt.Errorf("write pinned Edge CA: %w", err)
			}
			st.EdgeCAPath = caPath
		}
		if err := saveConnectorState(statePath, st); err != nil {
			return false, fmt.Errorf("persist connector state: %w", err)
		}
		f.apply(st)
		// The very first register proves enrollment with the Site's one-time bootstrap secret; the Edge then
		// remembers this connector's runtime-secret hash for every heartbeat and re-register after.
		*f.BootstrapSecret = tok.Bootstrap
		return true, nil
	}

	st, ok, err := loadConnectorState(statePath)
	if err != nil {
		return false, err
	}
	if !ok {
		return false, nil
	}
	f.apply(st)
	// Already enrolled: re-register with the runtime secret (empty bootstrap falls back to it), so a rotated Site
	// bootstrap secret is irrelevant here.
	*f.BootstrapSecret = ""
	return false, nil
}

// connectorStateMatchesToken reports whether a token describes the enrolment this connector already holds.
//
// Compared on what the token can actually establish — the deployment, the site, and the Edge to dial. The
// bootstrap secret is NOT compared: it is single-use, so a re-issued command for the same site carries a
// different one and still describes the same enrolment.
func connectorStateMatchesToken(st connectorState, tok connectorEnrollmentToken) bool {
	same := func(a, b string) bool {
		return strings.EqualFold(strings.TrimSpace(a), strings.TrimSpace(b))
	}
	return same(st.TenantID, tok.TenantID) && same(st.Site, tok.Site) && same(st.EdgeURL, tok.EdgeURL)
}
