package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ★★★ AN UNCAPPED LOG TOOK THE WHOLE DEPLOYMENT DOWN. Every service must get the cap, including one added
// later by somebody who never read this file — which is why it is applied by walking the rendered compose
// rather than by a list of service names to remember.
func TestEveryServiceInTheGeneratedComposeHasABoundedLog(t *testing.T) {
	rendered := `name: dsse

services:
  postgres:
    image: haproxy:2.9-alpine
    ports: ["5432:5432"]
  dsse-postgres-a:
    image: spilo
    volumes:
      - pg-a:/home/postgres/pgdata
  # a comment between services
  dsse-edge:
    image: dsse:release
  # ★ A SERVICE THAT DECLARES A YAML ANCHOR. The generated deployment has two, and one of them is the
  # database — the service whose cluster manager wrote 2.4 GB about itself. A cap that cannot see an anchor
  # covers everything except the thing it was written for.
  dsse-postgres-a: &dsse-postgres
    image: spilo

volumes:
  pg-a:

networks:
  default:
    name: dsse
`
	out := boundEveryServicesLog(rendered)

	if !strings.Contains(out, "x-dsse-logging: &dsse-logging") {
		t.Fatalf("the anchor was not defined:\n%s", out)
	}
	if strings.Index(out, "x-dsse-logging:") > strings.Index(out, "services:") {
		t.Fatal("the anchor must be defined BEFORE it is used, or compose refuses the file")
	}
	if got := strings.Count(out, "logging: *dsse-logging"); got != 4 {
		t.Fatalf("expected all 4 services capped, got %d:\n%s", got, out)
	}
	if !strings.Contains(out, "dsse-postgres-a: &dsse-postgres\n    logging: *dsse-logging") {
		t.Fatalf("a service declaring a YAML anchor was skipped:\n%s", out)
	}

	// ★ Only SERVICES. A volume or a network key is two spaces in and a colon too, and giving one a logging
	// key produces a file compose will not read.
	for _, mustNotFollow := range []string{"volumes:\n  pg-a:\n    logging:", "networks:\n  default:\n    logging:"} {
		if strings.Contains(out, mustNotFollow) {
			t.Fatalf("a non-service key was given a log cap:\n%s", out)
		}
	}
}

// A service whose settings somebody chose deliberately keeps them.
func TestAServiceThatAlreadyDeclaresLoggingIsLeftAlone(t *testing.T) {
	rendered := `services:
  dsse-edge:
    image: dsse:release
    logging:
      driver: syslog
  dsse-console:
    image: dsse-console:release
`
	out := boundEveryServicesLog(rendered)
	if got := strings.Count(out, "logging: *dsse-logging"); got != 1 {
		t.Fatalf("expected only the undeclared service to be capped, got %d:\n%s", got, out)
	}
	if !strings.Contains(out, "driver: syslog") {
		t.Fatal("the deliberate setting was removed")
	}
}

// ★★★ THE REPAIR SAID IT HAD REWRITTEN THIS FILE AND HAD NOT. The install guard — "this command made this
// file, leave whatever is there" — is right for install and wrong for repair, which exists so a deployment
// generated by an older installer can take a correction it cannot otherwise receive.
func TestRepairRewritesTheComposeFileAndInstallDoesNot(t *testing.T) {
	dir := t.TempDir()

	if err := writeComposeFileFor(dir, machineShape{holds: regionShapeStateBearing, edges: true}); err != nil {
		t.Fatalf("first render: %v", err)
	}
	first := readComposeForTest(t, dir)
	if !strings.Contains(first, "logging: *dsse-logging") {
		t.Fatal("a freshly generated deployment must already have bounded logs")
	}

	// Something on disk that install must not clobber.
	writeComposeForTest(t, dir, "# an operator edited this\nservices:\n  dsse-edge:\n    image: x\n")
	if err := writeComposeFileFor(dir, machineShape{holds: regionShapeStateBearing, edges: true}); err != nil {
		t.Fatalf("install over an existing file: %v", err)
	}
	if got := readComposeForTest(t, dir); !strings.Contains(got, "an operator edited this") {
		t.Fatal("install must leave a file that is already there alone")
	}

	// Repair is the explicit request to take the current installer's files.
	if err := rewriteComposeFileFor(dir, machineShape{holds: regionShapeStateBearing, edges: true}); err != nil {
		t.Fatalf("repair: %v", err)
	}
	got := readComposeForTest(t, dir)
	if strings.Contains(got, "an operator edited this") {
		t.Fatal("repair must actually rewrite — printing that it did while doing nothing is how a deployment " +
			"stays frozen at whatever the installer knew on the day it was minted")
	}
	if !strings.Contains(got, "logging: *dsse-logging") {
		t.Fatal("and the rewritten file must carry the correction the repair was run for")
	}
}

func readComposeForTest(t *testing.T, dir string) string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(dir, "docker-compose.yml"))
	if err != nil {
		t.Fatalf("read compose: %v", err)
	}
	return string(raw)
}

func writeComposeForTest(t *testing.T, dir, body string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, "docker-compose.yml"), []byte(body), 0o644); err != nil {
		t.Fatalf("write compose: %v", err)
	}
}
