package main

import (
	"fmt"
	"net"
	"path/filepath"
	"sort"
	"strings"
)

// frontdoor.go — the control plane's front door, and why a deployment has two control planes.
//
// ★★★ THE AUTHORITY MUST NOT BE A SINGLE POINT OF FAILURE. Everything that decides anything lives on the
// control plane: the configuration every Edge pulls, the enrolled inventory, and the one-time decisions —
// may this enrolment token be spent, has this identity already enrolled. An Edge whose control plane is gone
// keeps ENFORCING what it holds, which is the safe direction, but the deployment can no longer be
// administered, no device can enrol, and nothing new reaches the fleet. A generated deployment with one
// control plane has that as a single failure away.
//
// ★ THE ELECTION IS ALREADY IN THE PRODUCT, AND IT NEEDS NO NEW MACHINERY. The active control plane holds a
// Postgres SESSION-level advisory lock. A session lock is released the instant its session ends, so a crash —
// or a Postgres failover that kills the connection — releases it by itself, and the standby takes it on its
// next attempt. That is fencing without a second consensus system to run and get wrong.
//
// ★★ SO THE HEALTH CHECK IS THE ROUTING. GET /leader answers 200 on the leader and 503 on a standby, which
// means the front door needs no notion of DSSE at all: it sends traffic to whichever backend says 200. A
// standby is simply DOWN from its point of view, which is exactly right — a standby must not be routed to,
// because two nodes running the non-idempotent background work is worse than none.
//
// ★ AND THE TWO CONTROL PLANES MUST AGREE. They share the Postgres, and a node that holds no copy of its own
// follows the fleet rather than answering from an empty map of its own — which is what makes a warm standby
// warm rather than a second, emptier deployment.

// ★★★ AND THE DATABASE HAS A FRONT DOOR FOR THE SAME REASON. A control plane owns its Postgres, so an
// authority that is redundant means a DATABASE that is redundant — and a replica somebody has to promote by
// hand is a backup, not a failover: it survives the data and not the outage. The database cluster promotes by
// itself, and this routes to whichever node currently IS the primary, asked the same way: an HTTP check that
// answers 200 on the primary and something else everywhere else.
//
// writeFrontDoorConfig writes the control plane's front door configuration.
func writeFrontDoorConfig(dir string) error {
	path := filepath.Join(dir, "haproxy.cfg")
	if keepWhatIsThere(path) {
		return nil
	}
	// ★★★ THIS DOOR FOLLOWS LEADERSHIP ACROSS REGIONS TOO (2026-08-31, measured on the first three-region
	// deployment). It is the door an EDGE uses — DSSE_CONTROL_PLANE points at it — and it held only this
	// region's own control planes. In a region that joins, those are warm standbys and answer /leader with
	// 503, so the backend was empty and the Edge had nowhere to go: its enrolments sat in the outbox
	// ("delivered=0 still_pending=2") while every screen showed a healthy region.
	//
	// ★ THE REGION'S FRONT DOOR ON 443 ALREADY DID THIS. Two doors doing the same job — choose the node that
	// leads — and only the one a browser uses had been taught to look outside the region.
	peers := controlPlanePeers(dir)
	body := `# The control plane's front door. Generated by dsse-install.
#
# It routes to whichever control plane is the LEADER, which it discovers by asking: GET /leader answers 200 on
# the leader and 503 on a standby. Nothing here knows anything about DSSE — the health check IS the routing.
#
# TCP mode, not HTTP: the control plane serves TLS and the parties that reach it — Edges, connectors, the
# Console — verify it against the deployment's anchor. Terminating TLS here would put a certificate this
# deployment did not issue in front of the authority, and everything that pins the anchor would refuse it.
global
    log stdout format raw local0 info
    maxconn 4096

# ★★★ RESOLVE NAMES AT RUNTIME, NOT AT PARSE TIME (found by running it). By default HAProxy
# resolves every backend address while reading this file and REFUSES TO START if one does not resolve. A
# control plane that is still starting — or one that has crashed, which is the case this whole file exists
# for — is not yet a name, so the front door died with
#
#   'server cp_admin_backend/cp-a' : could not resolve address 'dsse-control-plane-a'
#
# A front door that cannot start when a backend is down is the opposite of what a front door is for.
# ★★★ THE DOOR REACHES THE NODES OVER IPv4, AND THAT IS NOT A PREFERENCE (measured by breaking
# both regions with it). Once the container network carries IPv6, Docker's DNS answers AAAA and this door
# re-resolves every backend to its v6 address — which changes the door's SOURCE address. An Edge trusts a
# PROXY protocol header only from the door addresses it was told (-trusted-front-doors), and those are the
# v4 addresses this deployment assigns by hand. So the Edge refused every connection and the door had no
# server: the symptom was that the region presented NO CERTIFICATE AT ALL, for any name, with nothing
# anywhere naming the cause.
#
# The Edge still egresses to the internet over IPv6. This is the one hop between the door and the Edge, and
# it stays on the family the trust was expressed in.
resolvers containers
    nameserver docker 127.0.0.11:53
    resolve_retries 3
    timeout resolve 1s
    timeout retry   1s
    hold valid   5s
    hold nx      1s
    hold other   1s

defaults
    mode    tcp
    log     global
    option  tcplog
    timeout connect 5s
    timeout client  60s
    timeout server  60s
    # A standby answering 503 is DOWN here, which is what we want: a standby must never be routed to, because
    # two nodes running the same non-idempotent background work is worse than neither running it.
    default-server inter 2s fall 2 rise 1

# The admin surface: where an Edge pulls its configuration, where the Console reads, and where an operator
# administers the deployment.
frontend cp_admin
    bind :9443
    default_backend cp_admin_backend

backend cp_admin_backend
    option httpchk GET /leader
    http-check expect status 200
    # ★★★ AND A NODE THAT STOPS LEADING LOSES THE CONNECTIONS IT ALREADY HAS (measured).
    # The health check decides where NEW connections go. Established ones stay where they are — so an
    # Edge that connected while this node led goes on talking to it after leadership moves, for as long
    # as its keep-alive lasts, which is indefinitely on a client that polls every ten seconds. Measured
    # on a two-region deployment: each control plane held HALF the fleet and neither could see the
    # other's, so /admin/fleet/config-status answered a different fleet depending on which process the
    # front door happened to pick — and every view of it looked complete.
    default-server on-marked-down shutdown-sessions
    server cp-a dsse-control-plane-a:9443 check check-ssl verify none resolvers containers init-addr last,libc,none resolve-prefer ipv4
` + peerControlPlaneServers(peers) + `

# The data surface: audit ingest, and everything a node ships to the authority.
frontend cp_data
    bind :8443
    default_backend cp_data_backend

backend cp_data_backend
    option httpchk GET /leader
    http-check expect status 200
    # ★★★ AND A NODE THAT STOPS LEADING LOSES THE CONNECTIONS IT ALREADY HAS (measured).
    # The health check decides where NEW connections go. Established ones stay where they are — so an
    # Edge that connected while this node led goes on talking to it after leadership moves, for as long
    # as its keep-alive lasts, which is indefinitely on a client that polls every ten seconds. Measured
    # on a two-region deployment: each control plane held HALF the fleet and neither could see the
    # other's, so /admin/fleet/config-status answered a different fleet depending on which process the
    # front door happened to pick — and every view of it looked complete.
    default-server on-marked-down shutdown-sessions
    # ★ THE CHECK IS ON THE ADMIN PORT even though the traffic is on the data one: leadership is a property of
    # the NODE, not of a listener, and asking the port that answers it avoids a second, differently-shaped
    # notion of health.
    server cp-a dsse-control-plane-a:8443 check check-ssl verify none port 9443 resolvers containers init-addr last,libc,none resolve-prefer ipv4
` + peerControlPlaneDataServers(dir) + `
`
	return writeContainerReadableFile(path, []byte(body))
}

// writeDatabaseFrontDoorConfig writes the front door for the database cluster.
func writeDatabaseFrontDoorConfig(dir string) error {
	path := filepath.Join(dir, "haproxy-postgres.cfg")
	if keepWhatIsThere(path) {
		return nil
	}
	body := `# The database's front door. Generated by dsse-install.
#
# It routes to whichever node is currently the PRIMARY, which it discovers by asking the cluster manager:
# GET /primary on 8008 answers 200 on the primary and 503 on a replica. Nothing here decides anything — the
# promotion is the cluster's decision and this only follows it.
#
# ★ THE PLAIN NAME IS THIS DOOR, and the nodes are -a and -b. Which of them is primary changes; the name
# everything connects to does not.
global
    maxconn 2048

defaults
    mode    tcp
    timeout connect 3s
    # A database connection is long-lived; a short client/server timeout here would sever a working session
    # for being quiet, which looks exactly like the failover this door exists to survive.
    timeout client  1h
    timeout server  1h
    default-server inter 2s fall 2 rise 1

resolvers containers
    nameserver docker 127.0.0.11:53
    resolve_retries 3
    timeout resolve 1s
    timeout retry   1s
    hold valid   5s
    hold nx      1s
    hold other   1s

frontend pg
    bind :5432
    default_backend pg_primary

backend pg_primary
    option httpchk GET /primary
    http-check expect status 200
    server pg-a dsse-postgres-a:5432 check port 8008 resolvers containers init-addr last,libc,none resolve-prefer ipv4
` + databaseFrontDoorPeers(dir) + `
`
	return writeContainerReadableFile(path, []byte(body))
}

// ★★★ AND THE AGENT PLANE HAS ONE TOO, FOR A DIFFERENT REASON. The control plane's front door exists to find
// the ONE node that may serve; this one exists because a region must present ONE address to devices while
// having MANY Edges behind it. A device is configured with the region it belongs to, not with a list of
// nodes: handing devices a list makes every node's address a promise the deployment can never withdraw, and
// a device holding a stale one steers to an address nobody serves.
//
// ★★★ IT MUST BE LAYER 4, AND THAT IS NOT A PERFORMANCE PREFERENCE. A device's identity IS its client
// certificate: the Edge admits a device by verifying the certificate at the handshake and refuses anything
// not in the enrolled inventory. An L7 load balancer terminates TLS, so what arrives at the Edge is a
// connection from the balancer with no client certificate at all — every decision the Edge makes about who
// this is would become "the balancer said so". So: TCP passthrough, and TLS terminates where the identity is
// checked.
//
// ★★ NO SESSION AFFINITY, DELIBERATELY. A device may land on any Edge and a reconnection may land on
// another. That is safe because an Edge holds no session state a device depends on — admission is per
// handshake against the inventory, and where a device is steering is carried in the fleet view's `edge`
// field precisely so a node can answer for a device connected elsewhere. Pinning devices to nodes would buy
// nothing and would make a drained node impossible to drain.
//
// ★★ AND IT ASKS THE EDGE WHETHER TO SEND IT ANYTHING. GET /healthz already answers for the two states that
// matter: a draining node (rolling upgrade) says 503 so new connections stop arriving while in-flight ones
// bleed out, and a node whose signing key cannot sign says 503 because it can no longer intercept a hostname
// it has not already cached. The Edge does not push itself out of rotation — a node broken enough to matter
// may be too broken to execute a removal, and a hung one fails the check simply by not answering.

// planeNames are the names this deployment answers on, one per plane.
//
// ★★★ THE PLANES ARE SPLIT BY NAME, NOT BY PORT NUMBER. Every mouth of a deployment is 443, because a device,
// a connector and an administrator all arrive through some enterprise's proxy and firewall, and a
// non-standard port is where they stop. Putting the admin plane on another port would hit exactly the same
// wall, because administrators are inside those networks too.
//
// With names, the certificate, the front door and the reachability of each plane can be handled separately
// while the port stays the one that is always open.
type planeNames struct {
	// BareHost is the deployment's own name, which every plane name and every per-node name hangs off.
	BareHost string
	Agents   string // devices and connectors
	Admin    string // the Console's browser, and the Console reaching the control plane
	Console  string
	// Recovery is the name an agent sends when the certificate it holds has expired — the way back for a
	// machine that was switched off for longer than its certificate lasted.
	//
	// ★★★ A DEPLOYMENT THAT ANNOUNCES NONE STRANDS EVERY DEVICE IT ENROLS (2026-08-25, measured on a
	// generated deployment after stranding a real one). The renewal endpoint is already served on the agent
	// port; what was missing is the NAME, and a name nobody announces is a name no agent can send. The Edge
	// measures who has adopted it and had been reporting "no way back" by device, into a log with no reader.
	Recovery string
	// Authority is where a NODE reaches the deployment's control plane: shipping what it recorded, reporting an
	// enrolment, reporting a connector that joined.
	//
	// ★★★ IT NEEDS A NAME BECAUSE REGIONS DO NOT SHARE A NETWORK (2026-08-25, found by walking a second
	// region). Inside one region a node reaches the authority by service name on the deployment's own network
	// and nothing else is needed. Across regions there is no such network — and the region door routed only
	// the agent and admin names, so a joining region's Edges could reach the control plane to READ their
	// configuration and had nowhere to send what they WRITE. Measured: a device enrolled through the second
	// region was admitted there and unknown to the authority, so blocking it answered 404 and removing it
	// stopped nothing.
	//
	// A third name on the same port, for the same reason the other two are: planes are separated by name, and
	// every mouth is 443.
	Authority string
	// Split is false when the deployment answers on an address rather than a name. Then there is no SNI to
	// route on, everything goes to the agent plane, and the deployment says so instead of pretending.
	Split bool
}

// planeNamesFor derives the per-plane names from what the operator said the deployment answers on.
func planeNamesFor(host string) planeNames {
	host = strings.TrimSpace(host)
	if host == "" || net.ParseIP(host) != nil {
		// ★ AN ADDRESS CANNOT BE PREFIXED. "agents.10.0.0.5" is not a name anybody can reach, and generating
		// it would produce a certificate and a front door that agree with each other and with nothing else.
		return planeNames{Agents: host, Admin: host, Console: host, Recovery: host, Authority: host, Split: false}
	}
	// ★★ AND A HOST THAT IS ALREADY A PLANE NAME IS NOT PREFIXED TWICE (2026-08-25). The door an operator
	// thinks of first is "agents.<their domain>", so giving it to -host is the natural mistake — and it
	// produced agents.agents.<domain> in the certificate, in the front door, and in the address handed to
	// connectors: three things that agree with each other and with nothing a client asks for.
	host = strings.TrimPrefix(host, "agents.")
	return planeNames{Agents: "agents." + host, Admin: "admin." + host, Console: "console." + host,
		Recovery: "recovery." + host, Authority: "authority." + host, BareHost: host, Split: true}
}

// writeRegionFrontDoorConfig writes the ONE door this deployment presents, on 443.
func writeRegionFrontDoorConfig(dir string, names planeNames) error {
	// ★ THE OTHER REGIONS' CONTROL PLANES. See the_edges_door_must_reach_the_other_regions.go: without them
	// this door can only find a leader that happens to be in this region.
	peers := controlPlanePeers(dir)
	if len(peers) == 0 {
		// ★★★ ONE ANSWER DRIVES BOTH DOORS (2026-08-28). The authority's door already derives its peers from
		// DSSE_REGION_ENDPOINTS — the map of this deployment's regions, which the operator must fill in
		// anyway — and the admin plane's door wanted a SECOND list, DSSE_CP_PEERS, that had to be kept in step
		// with it and had no place in deployment.env at all. Two lists for one fact is a way for the two to
		// disagree, and the disagreement is silent: the admin plane reaches the leader and the authority does
		// not, or the reverse, on a deployment where every screen is green.
		for _, d := range peerRegionDoorways(dir) {
			peers = append(peers, strings.Replace(d.check, "admin.", "admin.", 1)+":443")
		}
	}
	// ★ WHERE THIS REGION'S EDGES ACTUALLY ARE. On one host they are compose service names; on a deployment
	// with one component per machine they are real hosts, and only the operator knows what they are called.
	edgeBackends := edgeFleetBackends(dir)
	path := filepath.Join(dir, "haproxy-edge.cfg")
	if keepWhatIsThere(path) {
		return nil
	}
	routing := "    default_backend edge_fleet\n"
	if names.Split {
		routing = "" +
			"    # ★★★ ROUTED BY THE NAME THE CLIENT ASKED FOR, WITHOUT TERMINATING ANYTHING. req.ssl_sni reads\n" +
			"    # the name out of the ClientHello, which is plaintext and arrives before any key exchange. The\n" +
			"    # connection is still passed through byte for byte, so the device certificate the Edge admits\n" +
			"    # on survives — an L7 proxy that terminated here would destroy it.\n" +
			"    use_backend cp_admin_plane if { req.ssl_sni -i " + names.Admin + " }\n" +
			"    use_backend cp_data_plane  if { req.ssl_sni -i " + names.Authority + " }\n" +
			"    use_backend console_plane  if { req.ssl_sni -i " + names.Console + " }\n" +
			thisRegionsOwnPlaneNames(dir, names) +
			perNodeAdminRouting(dir, names) +
			"    default_backend edge_fleet\n"
	}
	body := `# The one door this deployment presents. Generated by dsse-install.
#
# ★★★ EVERY MOUTH IS 443. A device, a connector and an administrator all arrive through some enterprise's
# proxy and firewall, and a non-standard port is where they stop. The planes are separated by NAME:
#
#   ` + names.Agents + `   devices and connectors
#   ` + names.Admin + `   the Console's browser and the Console reaching the control plane
#   ` + names.Console + `   the Console itself
#   ` + names.Authority + `   nodes writing to the deployment's control plane, from any region
#
# ★★★ AND IT IS LAYER 4. A device's identity IS its client certificate, verified at the handshake against the
# enrolled inventory. Terminating TLS here would hand every Edge a connection with no client certificate on
# it, and every decision about who a device is would become "the front door said so".
global
    log stdout format raw local0 info
    maxconn 65536

resolvers containers
    nameserver docker 127.0.0.11:53
    resolve_retries 3
    timeout resolve 1s
    timeout retry   1s
    hold valid   5s
    hold nx      1s
    hold other   1s

defaults
    mode    tcp
    log     global
    option  tcplog
    timeout connect 5s
    # ★★★ A DEVICE'S TUNNEL IS LONG-LIVED AND MOSTLY IDLE, AND AN IDLE TIMEOUT HERE IS A DISCONNECTION. The
    # steering transport is one multiplexed connection a device holds for as long as it is running; a laptop
    # whose user is in a meeting sends nothing for an hour and is not idle in any sense that should cost it
    # its tunnel. The default 60s would cut every device in the fleet once a minute, and each cut is a
    # reconnection, a handshake and an admission check — self-inflicted load that looks like device churn.
    timeout client  24h
    timeout server  24h
    timeout tunnel  24h
    default-server inter 5s fall 3 rise 2

frontend region
    bind :443
    # Wait for the ClientHello so the name is readable. A connection that sends nothing is not a client of
    # this deployment, and the delay costs it rather than everybody else.
    tcp-request inspect-delay 5s
    tcp-request content accept if { req_ssl_hello_type 1 }
` + routing + `
backend edge_fleet
    # ★★★ A DEVICE MUST COME BACK TO THE NODE THAT IS HOLDING ITS SESSION (measured on a real Mac
    # against a two-Edge region). The agent's runtime-copy path opens a SESSION — a live TCP connection to the
    # destination, held open in ONE Edge process's memory — and then sends each exchange as a separate request
    # on a NEW connection. With leastconn those follow-ups went to the other Edge, which had never heard of the
    # session and answered, correctly, with session_not_found. Roughly half of every steered flow died, and the
    # device had no network.
    #
    # This is not fixable by sharing state: a session IS an open socket to somewhere else, and an open socket
    # cannot be handed to another process. The door has to send the device back where it came from.
    #
    # So: source affinity. All of one device's connections land on one Edge, which is also what the tunnel path
    # already needs and got by accident from holding a single connection. leastconn is kept as the tie-break
    # inside the hash so a node that is down is skipped rather than black-holing the devices hashed to it.
    #
    # ★ WHAT THIS COSTS, SAID OUT LOUD. Devices behind one NAT share a source address and land on one node, so
    # a region's balance is by SITE and not by device. That is the price of the datapath holding live sockets,
    # and it is the honest trade rather than a silent one — the alternative measured worse: it did not work.
    balance source
    hash-type consistent
    option httpchk GET /healthz
    http-check expect status 200
    # ★★★ send-proxy IS WHAT KEEPS THE DEVICE'S ADDRESS. Without it every device in this region arrives from
    # this container: one rate-limit bucket for the fleet, and a device list saying every machine is in the
    # same place. The Edge reads this header ONLY from the addresses named in -trusted-front-doors, which is
    # why these containers have fixed addresses in the compose file.
    #
    # The check is on the ADMIN port while the traffic is on the agent one: health is a property of the node.
` + edgeFleetServers(edgeBackends) + `
` + perNodeAdminBackends(dir, names) + `
backend cp_admin_plane
    # Whichever control plane is the LEADER. No send-proxy: this is not the agent plane, and the control
    # plane's callers are authenticated by session or token rather than by address.
    option httpchk GET /leader
    http-check expect status 200
    # ★★★ AND A NODE THAT STOPS LEADING LOSES THE CONNECTIONS IT ALREADY HAS (measured).
    # The health check decides where NEW connections go. Established ones stay where they are — so an
    # Edge that connected while this node led goes on talking to it after leadership moves, for as long
    # as its keep-alive lasts, which is indefinitely on a client that polls every ten seconds. Measured
    # on a two-region deployment: each control plane held HALF the fleet and neither could see the
    # other's, so /admin/fleet/config-status answered a different fleet depending on which process the
    # front door happened to pick — and every view of it looked complete.
    default-server on-marked-down shutdown-sessions
    server cp-a dsse-control-plane-a:9443 check check-ssl verify none resolvers containers init-addr last,libc,none resolve-prefer ipv4
    # ★★★ AND THE CONTROL PLANES IN THE OTHER REGIONS (measured the first time leadership landed
    # elsewhere). This backend knew only the two control planes on its own compose network — so when the leader
    # was in another region, the Edges HERE had no route to the authority at all, and the walk stopped with
    # "the door the Edges use never routed to a leader". The canonical says an Edge probes every control plane
    # and takes configuration from whichever region holds leadership; the flag-based path does that and this
    # door did not, so a deployment had two mechanisms and only one of them crossed a region.
    #
    # ★ EMPTY IS THE ORDINARY CASE for a deployment with one region, and the file says so rather than leaving
    # a reader to wonder whether something is missing.
` + peerControlPlaneServers(peers) + `
backend cp_data_plane
    # ★★★ WHERE A NODE WRITES TO THE AUTHORITY. Shipping what an Edge recorded, reporting an enrolment,
    # reporting a connector that joined — all of it goes to whichever control plane is the LEADER, and a
    # region that is not the leader's has no other way to reach it. Same leader check as the admin plane: a
    # standby must not receive writes, because two nodes taking them is worse than one.
    option httpchk GET /leader
    http-check expect status 200
    # ★★★ AND A NODE THAT STOPS LEADING LOSES THE CONNECTIONS IT ALREADY HAS (measured).
    # The health check decides where NEW connections go. Established ones stay where they are — so an
    # Edge that connected while this node led goes on talking to it after leadership moves, for as long
    # as its keep-alive lasts, which is indefinitely on a client that polls every ten seconds. Measured
    # on a two-region deployment: each control plane held HALF the fleet and neither could see the
    # other's, so /admin/fleet/config-status answered a different fleet depending on which process the
    # front door happened to pick — and every view of it looked complete.
    default-server on-marked-down shutdown-sessions
    server cp-a dsse-control-plane-a:8443 check check-ssl verify none port 9443 resolvers containers init-addr last,libc,none resolve-prefer ipv4
` + peerControlPlaneDataServers(dir) + `
backend console_plane
    server console dsse-console:8443 check check-ssl verify none resolvers containers init-addr last,libc,none resolve-prefer ipv4
`
	return writeContainerReadableFile(path, []byte(body))
}

// writeStandbyFrontDoorConfig writes the internal control-plane door for a region that runs a WARM STANDBY.
//
// ★ IT IS THE SAME DOOR WITH ONE SERVER BEHIND IT, AND THE SAME HEALTH CHECK. The check is what decides:
// GET /leader answers 200 only on the node that currently holds the deployment's advisory lock, so this
// region's Edges reach "the control plane" by the same service name and get an answer only while leadership
// is actually here. When it is not, this door has no healthy backend — which is correct, and is why the
// Edges also carry the deployment's per-region list (-config-source-endpoints): the door says "not here",
// and the list says where else to look.
//
// ★★ AND SESSIONS ARE CUT WHEN IT STOPS LEADING, for the reason measured on 2026-08-25: a health check
// decides where NEW connections go, and an Edge that polls every ten seconds never opens one. Without this,
// a standby that lost leadership would keep serving the Edges that were already talking to it.
func writeStandbyFrontDoorConfig(dir string) error {
	body := `# The internal control-plane door for a region that runs a WARM STANDBY. Generated by dsse-install.
#
# One server, and the same GET /leader check the state-bearing region's door uses. This region's Edges reach
# the control plane by service name; they are answered only while leadership is HERE, and their per-region
# endpoint list is what takes them elsewhere when it is not.
global
    log stdout format raw local0 info

resolvers containers
    nameserver docker 127.0.0.11:53
    resolve_retries 30
    timeout resolve 1s
    timeout retry 1s
    hold valid 5s
    hold nx 1s
    hold other 1s

defaults
    mode tcp
    log global
    option tcplog
    timeout connect 5s
    timeout client 60s
    timeout server 60s
    default-server inter 2s fall 2 rise 1

frontend cp_admin
    bind :9443
    default_backend cp_admin_backend

backend cp_admin_backend
    option httpchk GET /leader
    http-check expect status 200
    default-server on-marked-down shutdown-sessions
    server cp-a dsse-control-plane-a:9443 check check-ssl verify none resolvers containers init-addr last,libc,none resolve-prefer ipv4

frontend cp_data
    bind :8443
    default_backend cp_data_backend

backend cp_data_backend
    option httpchk GET /leader
    http-check expect status 200
    default-server on-marked-down shutdown-sessions
    # The check is on the ADMIN port even though the traffic is on the data one: leadership is a property of
    # the NODE, not of a listener.
    server cp-a dsse-control-plane-a:8443 check check-ssl verify none port 9443 resolvers containers init-addr last,libc,none resolve-prefer ipv4
`
	return writeContainerReadableFile(filepath.Join(dir, "haproxy-standby.cfg"), []byte(body))
}

// ★★★ A NAME THAT REACHES ONE NODE, ON 443 (2026-08-28, decided by the operator: "443").
//
// the_fleet_has_no_address.go records what was missing and why it was left open: half of -verify asks
// questions about NODES — is more than one control plane running, does every Edge hand devices the same
// region map, does every node run the same build — and a deployment built the way the canonical describes had
// no name that reached control plane A rather than B. Those questions were answered at ports published behind
// the door, which is the substitution a one-host lab makes, moved onto a private network. A green -verify said
// the fleet was consistent when reached at addresses the deployment does not offer to anyone.
//
// So each node gets one: <node>.admin.<host>, on 443, routed by SNI to that node and to no other.
//
// ★★ AND THE CERTIFICATE CARRIES A WILDCARD RATHER THAN A LIST. Edges are autoscaled — that is the whole
// reason their material is short-lived — so naming each node in the certificate would mean re-issuing the
// deployment's identity every time the fleet grew. One name, *.admin.<host>, survives a fleet that changes
// size, which a list cannot.
func perNodeAdminRouting(dir string, names planeNames) string {
	nodes := perNodeAdminTargets(dir)
	if len(nodes) == 0 {
		return ""
	}
	out := "    # ★★★ AND ONE NAME PER NODE, which is what makes the fleet questions askable as deployed:\n" +
		"    # <node>.admin.<host> reaches that node's admin surface and no other, on 443 like everything else.\n"
	for _, n := range nodes {
		out += fmt.Sprintf("    use_backend node_%s if { req.ssl_sni -i %s.admin.%s }\n",
			n.backend, n.node, names.BareHost)
	}
	return out
}

func perNodeAdminBackends(dir string, names planeNames) string {
	nodes := perNodeAdminTargets(dir)
	if len(nodes) == 0 {
		return ""
	}
	out := ""
	for _, n := range nodes {
		out += fmt.Sprintf(`
backend node_%s
    # ★ ONE SERVER, DELIBERATELY. The point of this name is that it reaches THIS node — a second server here
    # would make it another way of asking the fleet, which is what the plane names already are.
    option httpchk GET /healthz
    http-check expect status 200
    # ★★★ init-addr …,none, LIKE EVERY OTHER SERVER HERE (measured: without it the Edge machine's
    # doorway refused to start at all). ONE configuration is generated and carried to every machine, and the
    # nodes differ: an Edge machine has no control plane and a control-plane machine has no Edges. A server
    # whose name does not resolve HERE must be disabled, not fatal — the fleet and admin backends beside this
    # have always said so, and this one did not:
    #
    #	could not resolve address 'dsse-control-plane-a', disabling server.
    #	[ALERT] config : Failed to initialize server(s) addr.
    server %s %s:9443 check check-ssl verify none resolvers containers init-addr last,libc,none resolve-prefer ipv4
`, n.backend, n.node, n.host)
	}
	return out
}

type perNodeAdmin struct{ node, backend, host string }

// perNodeAdminTargets is every node this machine runs, by the name that will reach it.
func perNodeAdminTargets(dir string) []perNodeAdmin {
	out := []perNodeAdmin{}
	seen := map[string]bool{}
	add := func(host string) {
		host = strings.TrimSpace(host)
		if host == "" {
			return
		}
		if i := strings.IndexByte(host, ':'); i >= 0 {
			host = host[:i]
		}
		node := strings.TrimPrefix(host, "dsse-")
		// ★★★ AND THE REGION IS PART OF THE NAME (2026-08-28, measured on a two-region deployment). Every
		// region runs services called control-plane-a and edge-a, so <node>.admin.<host> named two different
		// machines in two different regions — and -verify, asking "is exactly one control plane the leader",
		// asked the same two nodes twice and answered "none of them holds leadership" about a deployment that
		// had one.
		//
		// ★ ONE LABEL, not two. The certificate carries *.admin.<host>, and a wildcard matches exactly one
		// label — so region-a-control-plane-a.admin.<host> verifies and control-plane-a.region-a.admin.<host>
		// does not.
		if region := strings.ToLower(strings.TrimSpace(readDeploymentEnv(dir)["DSSE_EDGE_REGION"])); region != "" {
			node = region + "-" + node
		}
		if node == "" || seen[node] {
			return
		}
		seen[node] = true
		out = append(out, perNodeAdmin{node: node, backend: strings.NewReplacer("-", "_", ".", "_").Replace(node), host: host})
	}
	// ★ THE DEFAULT FLEET IS NAMED TOO. edgeFleetBackends is what an OPERATOR wrote; empty means this
	// rendering's own two Edges, which edgeFleetServers falls back to — and a node reachable only when
	// somebody happened to list it is the gap this whole name exists to close.
	edges := edgeFleetBackends(dir)
	if len(edges) == 0 {
		edges = []string{"dsse-edge-a"}
	}
	for _, e := range edges {
		add(e)
	}
	// ★ ONE CONTROL PLANE PER MACHINE (2026-09-02). This named dsse-control-plane-b too, back when a machine
	// ran a pair of them behind a local haproxy — a shape the operator retired: "there is no point running two
	// control planes on one machine behind a haproxy". A per-node admin door for a container that is not in
	// the compose file is a haproxy backend whose name never resolves.
	for _, c := range composeServicesFor(controlPlaneNodeNames) {
		add(c)
	}
	return out
}

// ★★★ AND THIS REGION ANSWERS TO ITS OWN NAME (2026-08-28, measured on a deployment built from a plan).
//
// Once a deployment has more than one region, every plane needs a name that says WHICH — admin.<host> is
// answered by every site with its own doorway, which is what makes a client reach the region it is in and is
// exactly why it cannot name the other one. The plan hands those names out, DNS answers them, the certificate
// carries them, and the doorway routed none of them:
//
//	admin.region-a.dsse.lab -> region edge_fleet/<NOSRV>
//
// The name resolved, the certificate verified, and the door sent it to the Edge fleet because it matched
// nothing — on the CONTROL PLANE's machine, which has no Edge fleet. Every cross-region hop, and every
// operator asking a named region a question, landed there.
func thisRegionsOwnPlaneNames(dir string, names planeNames) string {
	region := strings.ToLower(strings.TrimSpace(readDeploymentEnv(dir)["DSSE_EDGE_REGION"]))
	if region == "" || names.BareHost == "" {
		return ""
	}
	// ★★★ EVERY REGION'S NAMES, NOT ONLY THIS ONE'S (2026-08-28, measured on a cross-region hop).
	//
	// This doorway forwards to the other regions in LAYER 4 — the stream is passed through byte for byte,
	// which is what keeps a device's client certificate intact. So the name that arrives at the receiving
	// door is the one the CLIENT asked for, not the peer's:
	//
	//	admin.region-b.dsse.lab -> region cp_admin_plane/cp-peer-1 -> region-a's door -> edge_fleet/<NOSRV>
	//
	// Region-a's door knew admin.region-a and nothing else, so the hop it was the target of ended in a
	// backend with no servers. Rewriting the SNI would mean terminating TLS here, which this whole
	// arrangement exists not to do.
	//
	// ★ AND ROUTING THEM ALL LOCALLY IS RIGHT, not a workaround. A region-qualified name says which DOOR to
	// arrive at; what the client needs once inside is the plane, and finding the leader wherever it is IS
	// the door's job. A name that reached one region's door and then insisted on that region would defeat
	// the routing it was carried through.
	regions := map[string]bool{region: true}
	for _, entry := range strings.Split(readDeploymentEnv(dir)["DSSE_REGION_ENDPOINTS"], ";") {
		if id, _, ok := strings.Cut(strings.TrimSpace(entry), "="); ok {
			if id = strings.ToLower(strings.TrimSpace(id)); id != "" {
				regions[id] = true
			}
		}
	}
	ordered := make([]string, 0, len(regions))
	for id := range regions {
		ordered = append(ordered, id)
	}
	sort.Strings(ordered)
	out := "    # ★★★ AND THE SAME PLANES UNDER EVERY REGION'S NAME. A deployment with more than one region\n" +
		"    # needs a name that says WHICH — the plain names are answered by every site with its own door.\n" +
		"    # ALL of them are routed here, not just this region's: a cross-region hop is layer 4, so the name\n" +
		"    # that arrives is the one the CLIENT asked for, and a door that knew only its own dropped every\n" +
		"    # hop it was the target of into a backend with no servers.\n"
	for _, id := range ordered {
		own := func(plane string) string { return plane + "." + id + "." + names.BareHost }
		out += "    use_backend cp_admin_plane if { req.ssl_sni -i " + own("admin") + " }\n" +
			"    use_backend cp_data_plane  if { req.ssl_sni -i " + own("authority") + " }\n" +
			"    use_backend console_plane  if { req.ssl_sni -i " + own("console") + " }\n" +
			"    use_backend edge_fleet     if { req.ssl_sni -i " + own("agents") + " }\n" +
			"    use_backend edge_fleet     if { req.ssl_sni -i " + own("recovery") + " }\n"
	}
	return out
}
