package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// launch.go — the commands that actually start this deployment.
//
// ★★★ WHY THESE ARE FILES AND NOT PROSE (2026-08-23, measured by walking it). The installer used to PRINT a
// start command. Following it exactly, the control plane refused to start nine times in a row, and the Edge
// twice more after that. Every one of the eleven was a real requirement the deployment has and the printed
// command did not carry:
//
//	-connector-secret, -workload-attestation-secret, -audit-ingest-token   generated into deployment.env, and
//	                                                                      the printed command named none of them
//	-admin-listen not on loopback                                         "the Console runs on a separate host"
//	-connector-runtime-secret-required                                    or one shared secret authenticates
//	                                                                      every connector
//	-workload-attestation-nonce-store                                     postgres on the control plane; on an
//	                                                                      Edge, memory plus the explicit
//	                                                                      -allow-ephemeral flag, because an
//	                                                                      enforcement Edge holds no database
//	-enrol-claim-fresh-deployment                                         a NEW deployment cannot prove it is
//	                                                                      not mid-migration, and refuses to start
//	-admin-auth-store                                                     or nothing can authenticate at all
//	-admin-token-break-glass-armed                                        or there is no way to create the first
//	                                                                      administrator — see below
//	-device-ca-cert/-key on the EDGE                                      the printed command put them on the
//	                                                                      control plane, and devices reach an Edge
//	-config-source-ca on the Edge                                         or it cannot verify the control plane
//
// A procedure with eleven gaps is not a procedure. So the installer writes two shell scripts that run, reading
// the secrets from deployment.env rather than carrying them in argv — where they would land in the operator's
// shell history and in every ps listing on the host.
//
// ★★ THE BREAK-GLASS ONE IS THE HEAVIEST, AND IT IS DELIBERATE HERE. -admin-token is a break-glass credential
// and it is INERT by default; the ordinary path is a named principal or an API token, and a deployment that has
// just been created has neither. So nothing can authenticate: not an administrator creating the first account,
// and not an Edge pulling its configuration — which does not fail loudly, it leaves the Edge running on the
// configuration it booted with, looking healthy.
//
// The generated control-plane script arms it, and says in the file that the first thing to do is create a named
// administrator and take the flag out. An installer that left this out would produce a deployment nobody can
// administer; one that armed it silently would leave a synthetic owner credential live forever.

// writeLaunchScripts writes start-control-plane.sh and start-edge.sh into dir. They are executable, they read
// deployment.env, and they carry every flag the walk found the deployment refuses to start without.
func writeLaunchScripts(dir string) error {
	at := func(name string) string { return filepath.Join(dir, name) }

	cp := `#!/usr/bin/env sh
# Start this deployment's CONTROL PLANE. Generated by dsse-install.
#
# It holds the authority: the configuration every Edge pulls, the enrolled inventory, the one-time decisions
# (may this enrolment token be spent, has this identity already enrolled), and the database. An Edge has none
# of those and refuses to start without a control plane to reach.
#
# Set DSSE_EDGE_BINARY to the product binary, and DSSE_POSTGRES_DSN to a database this control plane owns.
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
. "$here/deployment.env"

: "${DSSE_EDGE_BINARY:?set DSSE_EDGE_BINARY to the product binary}"
: "${DSSE_POSTGRES_DSN:?set DSSE_POSTGRES_DSN to a database this control plane owns}"
: "${DSSE_MIGRATION_DIR:?set DSSE_MIGRATION_DIR to the migrations directory shipped with the binary}"

# ★ THE ADMIN LISTENER MUST NOT BE ON LOOPBACK. The Console runs on a separate host, and the deployment says so
# by refusing to start otherwise.
DSSE_CP_LISTEN="${DSSE_CP_LISTEN:-0.0.0.0:8443}"
DSSE_CP_ADMIN_LISTEN="${DSSE_CP_ADMIN_LISTEN:-0.0.0.0:9443}"

# ★★★ THE REGION MAP IS AUTHORED HERE, and it travels to every Edge in the config bundle. Before this it was
# a flag on each node and nowhere else, so adding a region meant editing every Edge — and one that was missed
# stayed healthy while handing its devices a map without the new region in it. Set it once, here, when every
# region exists; the Edges receive it.
REGION_MAP=""
if [ -n "${DSSE_REGION_ENDPOINTS:-}" ]; then
  REGION_MAP="-region-endpoints=$DSSE_REGION_ENDPOINTS"
fi

# ★★★ A SECOND REGION THE FLEET CANNOT MOVE TO IS DECORATION (reported by win-dev-1).
#
# -steer-region-failover is the CP-signed posture that tells devices they MAY fail over, and it is a START-UP
# flag: there is no admin API for it, so a deployment that did not render it cannot be given region failover
# afterwards — the operator has to rebuild. Nothing here rendered it, so every deployment this installer has
# ever produced shipped with it off, however many regions it was told to have.
#
# Derived, not asked for. The operator already declares the regions in DSSE_REGION_ENDPOINTS; asking a second
# time in a second variable is how the two come to disagree, and that pair fails SILENTLY — a device that
# never fails over looks exactly like a device that never needed to.
REGION_FAILOVER=""
if [ "$(printf '%s' "${DSSE_REGION_ENDPOINTS:-}" | tr ';' '\n' | grep -c .)" -gt 1 ]; then
  REGION_FAILOVER="-steer-region-failover"
fi

# ★★★ WHERE A CONNECTOR DIALS, AND WHAT IT PINS. Without these the control plane REFUSES to issue a connector
# enrolment command at all — measured on a freshly generated deployment:
#
#   POST /admin/sites/<id>/enrollment-command -> 409
#   "this node cannot issue an enrollment command because it does not know the Edge address a connector
#    should dial"
#
# The refusal is the right behaviour: the alternative, which this deployment shipped once, is answering 200
# with a command whose token carries edge_url:"" and no pinned CA — the connector then rejects it before its
# first connection, and the Site bootstrap secret has already been rotated, so whatever the operator was
# holding is void. But a deployment that cannot issue the command has no connectors, and an installer that
# leaves this out produces one every time.
#
# The address is a CONNECTOR's, not an administrator's: the Edge device-facing door, reachable from inside the
# customer network.
#
# ★★★ AND IT IS THE REGION'S DOOR ON 443, NOT :8443 (measured by issuing one). This defaulted to
# "https://<host>:8443" — the Edge's own port INSIDE the container network, which is reachable from the Edge
# and from nowhere a connector runs. Every enrolment command a generated deployment issued carried it, so the
# command was self-contained and wrong.
#
# It is also the thing this deployment forbids in writing. enrolment_on_transport_port.go: "an agent touches
# ONE port, enrolment included; in production, 443 only", and "a port like 8443 appearing in the configuration
# handed to an agent must not happen at all" — with the installer named as where it happened. It was still
# happening here.
#
# So the default is the agent plane's NAME, on 443, which is what everything else this deployment hands out
# uses. An operator whose connectors reach the Edge some other way sets it; the point is that the default is
# an address that works rather than one that names the inside of a container.
# ★★★ WITH THE PORT THE AGENT PLANE IS ACTUALLY PUBLISHED ON (found by installing a connector into
# a deployment this installer generated). This derived https://agents.<host> and nothing else, so it means 443
# — which is right in production, where every plane is on 443, and wrong for every rendering that publishes the
# region doorway somewhere else. The connector enrolled from its token, then went for its identity and was
# refused:
#
#   Post "https://agents.localhost/enroll": dial tcp 127.0.0.1:443: connect: connection refused
#
# It had TWO working doors in the same profile, both with ports on them, and could not use either for this: the
# identity enrolment reads the token's single edge_url. So the port belongs here, at the one place that knows
# it. 443 is left implicit, because a URL that says :443 is a URL somebody eventually copies somewhere it is
# wrong.
if [ "${DSSE_REGION_PORT:-443}" = "443" ]; then
  DSSE_CONNECTOR_EDGE_URL="${DSSE_CONNECTOR_EDGE_URL:-https://${DSSE_AGENT_PLANE_NAME:-$EDGE_HOST}}"
else
  DSSE_CONNECTOR_EDGE_URL="${DSSE_CONNECTOR_EDGE_URL:-https://${DSSE_AGENT_PLANE_NAME:-$EDGE_HOST}:${DSSE_REGION_PORT}}"
fi

# ★★★ THE BREAK-GLASS CREDENTIAL IS ARMED ONLY UNTIL THIS DEPLOYMENT HAS AN ADMINISTRATOR.
#
# A control plane authenticates named principals and API tokens. A deployment that has just been created has
# neither, so nothing can authenticate — not somebody creating the first account, and not an Edge pulling its
# configuration. Arming breaks that circle.
#
# Leaving it armed is what would be wrong: it authorises as OWNER and attributes every act to a synthetic
# principal rather than to a person. So the SCRIPT decides, not whoever remembers. dsse-install
# -bootstrap-admin writes the marker below when the deployment has a real administrator, and from the next
# restart this flag is simply not passed.
BREAK_GLASS="-admin-token-break-glass-armed"
if [ -f "$here/runtime/admin-bootstrapped" ]; then
  BREAK_GLASS=""
fi

# ★★★ NO DEVICE CA ON THIS NODE — it does not issue device certificates. Devices reach an EDGE to enrol; the
# control plane holds the AUTHORITY: it verifies and spends the one-time token, and answers whether an identity
# has already been claimed. This file's own header has said so since it was written, and the flag was here
# anyway.
#
# ★★★ AND THAT IS WHAT LETS THE PAIR SHARE ITS STATE. A node that issues device certificates must keep its
# enrolled inventory in a store no other process rewrites wholesale — the guard refuses to start otherwise, and
# it is right to — and that is what kept the roster per node, so a failover made the deployment forget its
# fleet. A control plane that issues nothing carries no such requirement, and the roster can live where the
# authority's state belongs: in the database both control planes share.

# ★★★ AND WHO OPERATES IT (measured on the deployment this installer produced).
#
# The control plane draws a line between the organization that RUNS this deployment and the organizations it
# serves: an operator is answered about the whole deployment, a customer only about themselves. Which
# organization is the operator is declared with -operator-tenant-id, and this installer never passed it — so
# on a deployment it generated the answer was "nobody". Measured: /admin/session with the deployment's own
# credential returned is_operator_tenant false, and /admin/fleet/config-status returned the CUSTOMER
# projection — no node ids, no cluster ids, no per-node facts. Every deployment-wide question was therefore
# unanswerable BY ANY CREDENTIAL THE INSTALLER CAN CREATE, including the two this installer asks itself:
# -who-depends (who trusts this deployment, asked before tearing anything down) and whether the deployment
# signs under one authority.
#
# ★ THE VALUE IS THE SEED TENANT, WHICH IS WHAT THE CODE ALREADY ASSUMES. The break-glass credential is
# stamped with this node's own tenant and its audit line calls that the "seed_operator_tenant" — so the seed
# tenant was always meant to be the operator's, and the only thing missing was saying so. Declaring a
# DIFFERENT organization here would be worse than saying nothing: the deployment's only credential would then
# belong to a customer, and it could not seat the first administrator in the operator organization either.
#
# Customers are organizations created later, beside this one. They are not this one.
# ★★ THE LICENCE IS APPLIED HERE, AND ENFORCED ON THE EDGES. POST /admin/license lands on the authority, so
# this is the node that has to verify the vendor's signature; the Edges receive the signed file in the config
# bundle and verify it again with their own keys. Both stores are postgres so the standby control plane holds
# the same licence and the same accepted-serial high-water mark — a standby that forgot the mark would let an
# older file with more seats on it back in at the next failover.
#
# Off unless a vendor key is on disk: the absence of a licence is the ordinary state, and the OSS release is
# unlimited.
CP_LICENCE=""
if [ -f "$here/runtime/licence-vendor-keys.pem" ]; then
  CP_LICENCE="-license-vendor-keys=$here/runtime/licence-vendor-keys.pem -license-store=postgres -seat-allocation-store=postgres"
  if [ -n "${DSSE_LICENCE_MSSP_ID:-}" ]; then
    CP_LICENCE="$CP_LICENCE -license-mssp-id=${DSSE_LICENCE_MSSP_ID}"
  else
    echo "start-control-plane: a vendor signing key is present but DSSE_LICENCE_MSSP_ID is unset, so a licence" >&2
    echo "  issued to ANY MSSP verifies here. That check is what makes sign-then-encrypt safe." >&2
  fi
  if [ -f "$here/runtime/licence-recipient.key" ]; then
    CP_LICENCE="$CP_LICENCE -license-recipient-key=$here/runtime/licence-recipient.key"
  fi
fi

# ★★★ THE CONTROL PLANE ISSUES THE PROFILE, SO THE CONTROL PLANE HAS TO KNOW THE CONSOLE.
#
# The passthrough that keeps a steered administrator's Console reachable was wired into the EDGE — its
# launcher, and its /admin/agent-profile route — on a walk. It never reached a device. The profile a
# device is actually given is issued by the CONTROL PLANE, which had no idea what its own Console was called,
# so every profile went out with no passthrough_domains and every armed Mac loaded
# "transparent_passthrough domain_count=0 address_count=0". Measured today: console.tsubaki.lab answers 502
# through the tunnel, on a deployment where the Edge holds both flags correctly.
#
# Same shape as the front door this morning: the fix went into one of the two places that had to have it, and
# the one that was missed is the one on the path that matters.
CONSOLE_ORIGINS=""
if [ -n "${ADMIN_CONSOLE_ORIGINS:-}" ]; then
  CONSOLE_ORIGINS="-admin-console-origins=$ADMIN_CONSOLE_ORIGINS"
elif [ -n "${DSSE_REGION_ENDPOINTS:-}" ]; then
  derived="$(printf '%s' "$DSSE_REGION_ENDPOINTS" | tr ';' '\n' \
    | sed -n 's/^[^=]*=//p' | sed 's#//agents\.#//console.#' | tr '\n' ',' | sed 's/,$//')"
  [ -n "$derived" ] && CONSOLE_ORIGINS="-admin-console-origins=$derived"
fi

CONSOLE_ORIGIN=""
if [ -n "${ADMIN_CONSOLE_ORIGIN:-}" ]; then
  CONSOLE_ORIGIN="-admin-console-origin=$ADMIN_CONSOLE_ORIGIN"
fi

# ★★★ THE ROOT THIS NODE NAMES IN DEVICE PROFILES, AND SIGNS NOTHING WITH (found by walking a Mac
# onto a deployment built from the published tree). A control plane holds no interception key — signing stays
# with the Edges — but it is the node the Console asks for a device's configuration. Without this, a profile
# it issued named no interception root at all, and the chain that starts there is: profile ->
# agent_config.trusted_ca_bundle -> the PEM bundle the macOS package points SSL_CERT_FILE at. With the first
# link empty every link after it is empty, so a device that WAS being inspected could verify nothing and no
# message anywhere said why. Absent is fine — a deployment that inspects nothing names nothing.
PROFILE_INTERCEPTION_ROOT=""
if [ -f "$here/lantern_dsse_interception_root_ca.pem" ]; then
  PROFILE_INTERCEPTION_ROOT="-deployment-interception-root-cert=$here/lantern_dsse_interception_root_ca.pem"
fi

# ★★★ THE CONTROL PLANE HOLDS THE DISTRIBUTION, BECAUSE IT IS THE ONLY NODE THAT CAN CARRY IT ACROSS REGIONS.
#
# What devices check before they will talk to an Edge at all travels in the signed config bundle, and the
# publisher of that section is whichever node HOLDS a distribution. Without one here, the section is never in
# a bundle and a certificate added through the Console reaches only the Edge the Console happened to reach.
#
# The set an Edge serves is still the Edge's own; this is authorship, not service. An Edge that hears nothing
# from here keeps what it booted with, which is the same anchor this node starts from.
# The anchor only — this node is given that file and not the signing intermediate the Edges fall back to, and
# a branch naming a file a service does not mount starts, finds nothing, and reports something else.
TRUST_BUNDLE=""
if [ -f "$here/deployment-anchor.pem" ]; then
  TRUST_BUNDLE="-trust-bundle-ca=$here/deployment-anchor.pem"
  TRUST_BUNDLE="$TRUST_BUNDLE -trust-bundle-serial=${DSSE_TRUST_BUNDLE_SERIAL:-1}"
  # ★★★ IN THE DEPLOYMENT'S OWN DATABASE, NOT ON THIS MACHINE'S DISK. Only the LEADING control plane serves
  # the config bundle, and leadership moves. A node that has never led sits at the serial it booted with while
  # the fleet is far past it; the moment it takes over, the next certificate an operator adds is numbered from
  # ITS serial, lands below the fleet's high-water mark, and is discarded by every Edge as a replay — with the
  # Console reporting it added. A serial that only ever goes up can only hold if every node that might issue
  # one counts from the same place.
  TRUST_BUNDLE="$TRUST_BUNDLE -transport-trust-store=postgres"
  # And where this node kept it before that, so an upgrade does not restart the authority below the serial the
  # fleet is already serving. Read once; absent on a deployment that never had one.
  TRUST_BUNDLE="$TRUST_BUNDLE -transport-trust-carried-from=$DSSE_CP_STATE_DIR/transport-trust.json"
  # And the assertions that OPEN a withdrawal, for the same reason: an operator vouches for a device against
  # whichever node is leading, and a different node judges the withdrawal. On one node's disk the assertion
  # disappears when leadership moves and the withdrawal is silently refused again.
  TRUST_BUNDLE="$TRUST_BUNDLE -transport-anchor-ack-store=postgres"
fi

exec "$DSSE_EDGE_BINARY" -control-plane \
  -listen="$DSSE_CP_LISTEN" -admin-listen="$DSSE_CP_ADMIN_LISTEN" \
  $CP_LICENCE \
  -tls-cert="$here/management.crt" -tls-key="$here/management.key" \
  -policy="$here/policy.json,$here/policy-egress.json" -bundle="$here/policy-bundle.json" \
  -schema-dir="$here/schemas" \
  -agent-policy-signing-key="$here/agent-policy-signing.key" \
  -operator-tenant-id="${DSSE_OPERATOR_TENANT:-tenant_default}" \
  -deployment-name-suffix="$EDGE_HOST" \
  -renewal-recovery-sni="${DSSE_RECOVERY_SNI:-}" \
  -state-dir="${DSSE_CP_STATE_DIR:-$here/cp-state}" \
  -agent-update-manifest-dir="${DSSE_CP_STATE_DIR:-$here/cp-state}/agent-updates" \
  -log-dir="${DSSE_CP_STATE_DIR:-$here/cp-state}/logs" \
  -postgres-dsn="$DSSE_POSTGRES_DSN" \
  -migration-dir="$DSSE_MIGRATION_DIR" -postgres-run-migrations \
  -site-store=postgres \
  -admin-export-job-store=postgres \
  -agent-telemetry-store=postgres \
  -usage-meter-store=postgres \
  -observed-exclusion-store=postgres \
  -hot-store=clickhouse \
  -admin-auth-store=postgres \
  -enrolled-inventory-store=postgres \
  -inspection-posture-store=postgres \
  -connector-registry-store=postgres \
  -workload-attestation-nonce-store=postgres \
  -first-party-accounts -first-party-store=postgres \
  -tenant-model-store=postgres \
  -agent-update-pin="$(cat "$here/agent-update-signing.pub" 2>/dev/null | tr -d '\n')" \
  -agent-update-publisher="${DSSE_AGENT_PUBLISHER:-}" \
  -tenant-device-authority-store=postgres \
  -tenant-transport-authority-store=postgres \
  -tenant-interception-authority-store=postgres \
  -agent-updates-store=postgres \
  -agent-rollout-store=postgres \
  -steer-exclusion-store=postgres \
  $CONSOLE_ORIGIN $CONSOLE_ORIGINS \
  -admin-token="$ADMIN_TOKEN" \
  -connector-secret="$CONNECTOR_SECRET" \
  -workload-attestation-secret="$WORKLOAD_SECRET" \
  -audit-ingest-token="$AUDIT_INGEST_TOKEN" \
  -connector-runtime-secret-required \
  -enrol-claim-fresh-deployment \
  -transport-tenant-ca-registry=postgres \
  -transport-tenant-ca-registry-carried-from="$here/device-ca-registry.json" \
  -hot-store-clickhouse-endpoint="$DSSE_CLICKHOUSE_ENDPOINT" \
  -hot-store-clickhouse-user=dsse -hot-store-clickhouse-password="$CLICKHOUSE_PASSWORD" \
  -cold-archive-endpoint="$DSSE_ARCHIVE_ENDPOINT" -cold-archive-bucket="$DSSE_ARCHIVE_BUCKET" \
  -cold-archive-access-key="$MINIO_ROOT_USER" -cold-archive-secret-key="$MINIO_ROOT_PASSWORD" \
  -audit-chain-store="$DSSE_CP_STATE_DIR/audit_chain.json" \
  -audit-ingest-receiver-token="$AUDIT_INGEST_TOKEN" \
  -audit-ingest-client-ca="$here/management-ca.crt" \
  -audit-ingest-authority="$here/audit-ingest-authority.json" \
  $REGION_MAP $REGION_FAILOVER \
  -connector-enrollment-edge-url="$DSSE_CONNECTOR_EDGE_URL" \
  -connector-enrollment-edge-ca="$here/deployment-anchor.pem" \
  $PROFILE_INTERCEPTION_ROOT \
  $TRUST_BUNDLE \
  $BREAK_GLASS \
  "$@"

# ★★★ AND THE BEARER IS NOT ENOUGH, BY DESIGN. The receiver refuses a shipment it cannot attribute to a node,
# because the bearer is shared by every Edge in the deployment: anything holding it could otherwise write any
# organization's audit history and the fleet numbers an operator makes rollout decisions from. So the Edge
# presents a client certificate, the control plane verifies it against the OPERATOR authority, and the map
# below says which organizations that identity may speak for.
#
# ★★ THE MAP NAMES ONE ORGANIZATION AND NOT "*". A second organization joining this deployment must be added
# here, and until it is, its records are refused with a 403 that names the reason. That is the failure this
# should have: "*" would mean any Edge may write any customer's history, which is the thing the certificate
# check exists to prevent.
#
# ★★★ TWO FLAGS, ONE SECRET, AND THE CONTROL PLANE HELD THE SENDER'S (found by reading the Edge's
# own log). -audit-ingest-token is what a node SHIPS with; -audit-ingest-receiver-token is what the control
# plane REQUIRES, and it is also what REGISTERS the receiving route at all. This script set only the first, so
# POST /audit-ingest did not exist and every shipment came back 404. Nothing was lost — the shipper retains and
# retries, and it said so in the plainest terms available:
#
#   ★ audit ship: FAILING — audit ingest returned HTTP 404 (2 record(s) pending, retained and retried;
#     nothing is lost yet, but no history is reaching the control plane)
#
# which is the only reason this took minutes instead of a week. A route that does not exist answers exactly
# like a route that is not authorised.
#
# ★★★ THE INSPECTION POSTURE IS NAMED BECAUSE A CONTROL PLANE AUTHORS IT. A store whose flag is unset follows
# the shared database only when nothing forbids it, and the posture is on the "stays per node" list —
# deliberately, so an EDGE never drifts onto shared state. The tree says what to do about it in as many words:
# "a control plane, which AUTHORS rather than receives, is given an explicit backend".
#
# ★★★ AND THE ENROLLED INVENTORY IS NOT NAMED, THOUGH IT HAS THE SAME PROBLEM AND A WORSE ONE. Measured on the
# pair: cp-a held the fleet's roster and cp-b held nothing. The front door serves whichever is leader, so the
# bundle an Edge received named five devices or none depending on the moment — and an Edge receiving none keeps
# its own, which is the lockout-safe rule working exactly as intended. Every node ended up with a DIFFERENT
# roster, and blocking a device stopped it nowhere.
#
# Pointing it at the shared database does not fix that; the product REFUSES TO START, and it is right to:
#
#   REFUSING TO START: this Edge issues device certificates and keeps its enrolled inventory in a store other
#   processes rewrite wholesale. That store is an unconditional last-write-wins UPSERT, so a second node
#   saving an older snapshot erases enrolment records and admin disables from it without a word.
#
# So this is an OPEN gap in the design rather than a missing flag, and -verify measures it: "the control
# planes hold the same authority" asks each peer directly and reports when they disagree. See
# docs/architecture/ for what it would take — the store's writes have to become incremental before two
# authorities can share one.
#
# ★★★ AND THE FOUR THAT MAKE AN ORGANIZATION AN ORGANIZATION (found by creating one in the
# Console and trying to give it its own PKI). The canonical is that every organization has its own tree —
# device identity, transport, interception — so that no single key can impersonate two of them. A generated
# deployment had nowhere to keep any of it:
#
#	-tenant-model-store                 the catalogue itself. Empty = in-memory: a tenant created in the
#	                                    Console is gone on the next restart
#	-tenant-device-authority-store      whose device CA admits whose devices
#	-tenant-transport-authority-store   "Empty = this node issues no per-organization transport material,
#	                                    and Edges cannot assemble themselves"
#	-tenant-interception-authority-store "Empty = this node hands Edges no interception material"
#
# The Console offers all of it — "Register this tenant's device CA", "Load this tenant's interception CA",
# with a time-boxed elevation the customer can see — and the last of those answered
#
#	interception is not enabled on this node, so it cannot say what this organization's traffic is
#	inspected under
#
# because the flag was empty, so the node had no place to put it. Every organization therefore fell back to
# the deployment's ONE shared interception root, and the Edge reported exactly that:
# configured=shared, per_tenant_issuers=0.
#
# ★★ AND -verify SAID IT WAS FINE, because it asks whether the fleet signs under ONE authority — which is the
# opposite of the question. Being one authority is what per-organization independence is NOT.
#
# ★★★ THE STORES THAT SELECT A BACKEND ARE NAMED HERE, because -state-dir cannot default them. It gives a
# store a PATH; these take memory | postgres | clickhouse, so a path is not an answer and their default is
# memory. On a control plane that owns a database, memory is never the right one: every restart is a silent
# reset of the export queue, the agent telemetry, the usage meter, the observed exclusions and the hot store.
#
# ★ AND ONLY ON THE CONTROL PLANE. An Edge holds no database, so the same flags there would be wrong in the
# other direction — an Edge's observed exclusions are shipped to the control plane, not kept.
#
# ★★★ -site-store=postgres, OR NO CONNECTOR CAN EVER ENROL (found by walking the connector path
# on a generated deployment). Sites travel to the Edges in the config bundle, and the section carries a
# COMPLETE flag: a control plane whose own Site store is volatile says so, and every Edge then keeps what it
# has rather than being wiped by a store that has just restarted empty. That guard is right.
#
# The default Site store is IN-MEMORY. So a generated control plane published complete=false on every bundle,
# for ever, and the Edge logged
#
#   config_bundle_sites_kept_local reason="the control plane did not report a complete Site catalog"
#
# once per poll while holding zero Sites. A connector then presents its Site's bootstrap secret to an Edge
# that has never heard of the Site, and is refused with "the bootstrap secret is not this Site's" — which is
# true, and says nothing about the missing flag three components away.
#
# ★ -first-party-accounts IS WHAT MAKES THE FIRST ADMINISTRATOR POSSIBLE (found by walking it).
# Without it POST /admin/admins/invite answers 503 "first-party admin accounts are not enabled", so a
# deployment that has armed the break-glass credential still cannot create the named account that would let it
# be disarmed. The store is postgres rather than memory because a credential lost on the next restart is not a
# credential — it is the same lockout one restart later.
#
# ★★★ TWO FLAGS BELOW ARE FOR A DEPLOYMENT THAT HAS JUST BEEN CREATED, AND BOTH SHOULD COME OUT.
#
#   -enrol-claim-fresh-deployment
#       declares that this deployment has never enrolled a device, so there is no existing fleet to import into
#       the shared identity claim. Only the party that created the deployment can say that. On a deployment
#       that HAS enrolled devices it is a lie, and the cost of the lie is a second issuer handing out a
#       certificate for a device name already in use.
#
#   the break-glass credential (armed above while admin-bootstrapped is absent)
#       makes -admin-token an owner-level credential attributed to a synthetic principal. Without it a new
#       deployment cannot be administered AT ALL — there are no named principals and no API tokens yet, so
#       creating the first administrator is refused, and so is every Edge's configuration pull.
#
#       ★ IT CLOSES ITSELF. Run: dsse-install -bootstrap-admin -dir <this directory> -control-plane <admin URL>
#       -admin-email <address>. That creates the deployment's first named administrator, proves it can sign in,
#       and writes admin-bootstrapped here. From the next restart this script does not arm anything.
`

	edge := `#!/usr/bin/env sh
# Start an EDGE of this deployment. Generated by dsse-install.
#
# An Edge enforces. It holds NO database: its configuration comes from the control plane, its durable shared
# state lives there, and the one-time decisions are asked of it. Set DSSE_CONTROL_PLANE to that control plane's
# admin URL — an Edge refuses to start without one, so the install order is enforced rather than recommended.
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
. "$here/deployment.env"

: "${DSSE_EDGE_BINARY:?set DSSE_EDGE_BINARY to the product binary}"
: "${DSSE_CONTROL_PLANE:?set DSSE_CONTROL_PLANE to the control plane admin URL, e.g. https://cp.example:9443}"

DSSE_EDGE_LISTEN="${DSSE_EDGE_LISTEN:-0.0.0.0:8443}"
DSSE_EDGE_ADMIN_LISTEN="${DSSE_EDGE_ADMIN_LISTEN:-0.0.0.0:9443}"

# ★★★ THE OUT-OF-BAND STEP-UP HAD NO ADDRESS, SO IT NEVER HAPPENED (measured on a live deployment
# with a real device).
#
# An egress rule with access=authenticate compiles, reaches the Edge, and enforces: a steered Mac asking for
# a destination under such a rule was answered
#
#	HTTP/2 401     {"decision":"require_reauthentication","actions":[{"type":"prompt_reauthentication"}]}
#
# and that is the whole ceremony. The response carries no step-up URL, no X-Dsse-Stepup-Url header, and a
# browser Accept gets the same bare 401 instead of the redirect the code is written to send — because
# isAuthRedirectCase returns false when brokerBaseURL is empty, and NOTHING this installer generates ever set
# -clientless-base-url. The broker, the grant store, the device binding, the mux STEPUP frame, the macOS agent
# that opens the URL and the Windows agent that reads the header are all implemented and none of them could
# fire. A control that holds a flow and cannot say where to go is a control that only denies.
#
# The base URL is the RP base for the OIDC redirect_uri, so it has to be a name the USER'S BROWSER resolves
# and reaches — which is the region's agent plane, the same door the device already uses, and the same
# derivation the connector's edge URL uses two files down to the port.
# ★★★ AND IT IS THIS REGION'S DOOR, NOT THE DEPLOYMENT'S (measured on three regions).
#
# Every region rendered the same deployment-wide name, agents.<host>, which resolves to ONE region. Two
# consequences, and the first one happens with nothing broken at all:
#
#  1. A flow held in osaka sent the user to tokyo-east's Edge. That Edge runs the ceremony and mints the
#     grant — in ITS OWN memory, because an Edge is zero-DB — and the Edge that is holding the flow looks for
#     that grant in its own and finds none. The user authenticates successfully and is held again.
#  2. When the region behind that one name is the one that fails, EVERY region's step-up points at a dead
#     address, including the regions the devices correctly failed over to.
#
# The right address is the door the device is already using, in the region it is currently in: it follows the
# device across a failover for free, and it keeps the ceremony and the flow on the same node.
# ★★★ A for/case, NOT A read LOOP IN A PIPELINE (measured: the first version took two of three
# regions down, and the second would not parse).
#
# A while-read over a pipeline has two traps at once. The last entry has no trailing separator, so read
# returns non-zero and the body never runs for it — whichever region is LAST in the map silently gets no
# portal. And the loop's status is its last iteration's, which becomes the pipeline's, which becomes the
# command substitution's: on every region except the one that matched last, the assignment ended non-zero and
# the set -eu at the top of this script killed it before it printed a line. The Edge exited 1 with EMPTY logs
# and the region's front door served a backend that was not there.
#
# for over the map with a case is neither: both always exit 0, every entry is visited, and there is no
# subshell. The endpoints carry no spaces, so splitting on them is safe.
DSSE_CLIENTLESS_REGION_URL=""
for dsse_region_entry in $(printf '%s' "${DSSE_REGION_ENDPOINTS:-}" | tr ';' ' '); do
  case "$dsse_region_entry" in
    "${DSSE_EDGE_REGION:-__no_region__}"=*) DSSE_CLIENTLESS_REGION_URL="${dsse_region_entry#*=}" ;;
  esac
done
if [ -n "$DSSE_CLIENTLESS_REGION_URL" ]; then
  DSSE_CLIENTLESS_BASE_URL="${DSSE_CLIENTLESS_BASE_URL:-$DSSE_CLIENTLESS_REGION_URL}"
elif [ "${DSSE_REGION_PORT:-443}" = "443" ]; then
  # No region map yet — a single-region deployment, or one still being built. The deployment-wide name is
  # then the only one there is, and it names this region.
  DSSE_CLIENTLESS_BASE_URL="${DSSE_CLIENTLESS_BASE_URL:-https://${DSSE_AGENT_PLANE_NAME:-$EDGE_HOST}}"
else
  DSSE_CLIENTLESS_BASE_URL="${DSSE_CLIENTLESS_BASE_URL:-https://${DSSE_AGENT_PLANE_NAME:-$EDGE_HOST}:${DSSE_REGION_PORT}}"
fi
CLIENTLESS="-clientless-base-url=$DSSE_CLIENTLESS_BASE_URL"

# ★★★ AND THE CERTIFICATE A BROWSER VALIDATES THERE IS THE OPERATOR'S (decided after walking the
# ceremony on a real device).
#
# The portal is served on this Edge, but a browser is sent to it and has no reason to trust what this
# deployment mints: the only deployment root a steered device carries is its organization's INTERCEPTION
# root. Borrowing that root would make the interception authority vouch for a real server — mistrust or
# rotate it and the step-up, a recovery path, goes with it. Steering the portal so it is intercepted like any
# site was measured and is not available: the device's transparent passthrough matches by ADDRESS, and every
# name this deployment answers to shares one address per region, so the portal is passed through with the
# agent's own control channel.
#
# The identity provider is not part of this product. It is the customer's — Okta, Entra ID — reached over a
# publicly trusted certificate, and the DSSE hop in between is a browser-facing page like any other. So the
# operator drops a certificate for the portal's name beside this script and it is used; without one the
# portal keeps the agent plane's certificate, which is right for a lab and shows as a browser warning rather
# than as a trust decision made quietly on their behalf.
# ★ A DIRECTORY, NOT TWO FILES. A bind mount of a file that does not exist creates a DIRECTORY in its place
# and the host can then never write the file — the same trap the runtime/ mount above carries a note about.
# The directory is always there and usually empty; dropping the pair into it is the whole act.
if [ -f "$here/clientless/tls.crt" ] && [ -f "$here/clientless/tls.key" ]; then
  CLIENTLESS="$CLIENTLESS -clientless-tls-cert=$here/clientless/tls.crt -clientless-tls-key=$here/clientless/tls.key"
fi

# ★★★ AND A DEPLOYMENT THAT ALREADY EXISTS GETS ONE TOO.
#
# STEPUP_BINDING_SECRET is generated with the other secrets, so every deployment built from here has it. A
# deployment built BEFORE it existed does not, and a repair does not add secrets — correctly: it must never
# touch them. But the failure that leaves is silent, and worse than the one it avoids, because a repair runs
# per machine and INVENTING one locally would give every Edge a different key while each believed it had a
# shared one.
#
# So the fallback is a secret every Edge in a deployment already holds, identically, carried when the machine
# was packed. The Edge does not use it as a key: it derives one under its own domain separator (see
# newDeviceBindingSignerFromSecret), so the derived key is not the connector secret and cannot be used as it.

# ★★★ THE FLEET CREDENTIAL EXISTS ONLY AFTER THE BOOTSTRAP, AND PASSING IT BEFORE IS WORSE THAN NOT PASSING IT.
#
# dsse-install generates EDGE_CP_TOKEN with the other secrets, but until -bootstrap-admin REGISTERS it with the
# control plane it is a random string nobody knows. Passing it then does not fall back to anything: the pull is
# refused, and the Edge runs on what it booted with, healthy, receiving nothing. Measured — the check caught it
# as "the Edge has applied NOTHING from the control plane".
#
# So this script asks the same question the control plane's does. Before the bootstrap there is one credential
# in this deployment and the Edge uses it; after, the Edge has its own, read-scoped one.
FLEET_TOKEN=""
if [ -f "$here/runtime/admin-bootstrapped" ]; then
  FLEET_TOKEN="-steer-exclusion-source-token=$EDGE_CP_TOKEN"
fi

# ★★★ WHICH REGION THIS EDGE IS IN, AND WHICH REGIONS THE DEPLOYMENT HAS. Both are read from deployment.env
# rather than written here, because every Edge runs this same script and these are the two facts that differ.
#
# ★ ON AN EDGE THE ENTRY LIST IS THE FLOOR, NOT THE ANSWER. It is what this node serves until its first
# successful pull; from then on the CONTROL PLANE's map replaces it, which is why setting it here is optional
# and setting it on the control plane is not. Leave it empty on an Edge unless this node must be able to
# answer before it has ever reached the control plane.
REGION=""
if [ -n "${DSSE_EDGE_REGION:-}" ]; then
  REGION="-edge-region-id=$DSSE_EDGE_REGION"
fi
REGION_MAP=""
if [ -n "${DSSE_REGION_ENDPOINTS:-}" ]; then
  REGION_MAP="-region-endpoints=$DSSE_REGION_ENDPOINTS"
fi

# ★★★ A SECOND REGION THE FLEET CANNOT MOVE TO IS DECORATION (reported by win-dev-1).
#
# -steer-region-failover is the CP-signed posture that tells devices they MAY fail over, and it is a START-UP
# flag: there is no admin API for it, so a deployment that did not render it cannot be given region failover
# afterwards — the operator has to rebuild. Nothing here rendered it, so every deployment this installer has
# ever produced shipped with it off, however many regions it was told to have.
#
# Derived, not asked for. The operator already declares the regions in DSSE_REGION_ENDPOINTS; asking a second
# time in a second variable is how the two come to disagree, and that pair fails SILENTLY — a device that
# never fails over looks exactly like a device that never needed to.
REGION_FAILOVER=""
if [ "$(printf '%s' "${DSSE_REGION_ENDPOINTS:-}" | tr ';' '\n' | grep -c .)" -gt 1 ]; then
  REGION_FAILOVER="-steer-region-failover"
fi

# ★★★ WHO IS ALLOWED TO SAY WHERE A DEVICE CAME FROM. A region has ONE agent-facing address, so every device
# in it arrives through a front door — and that front door must pass TCP through untouched, because a device's
# identity is its client certificate and an L7 proxy that terminates TLS destroys it. What survives the front
# door is the connection; what does not is the address it came from. Every device would then appear to be AT
# the front door: one rate-limit bucket for the whole fleet, and a device list saying every machine on earth
# is in the same place.
#
# The front door states the original address in a PROXY protocol header before the first byte of TLS, and this
# names whose statement is believed. Empty reads no header from anyone, which is correct with no front door
# and is NOT "believe anybody": a peer that can choose its own source address chooses every decision keyed on
# it, starting with the rate limit.
# ★★★ THE WAY BACK, ANNOUNCED. An agent whose certificate expired while its machine was switched off reaches
# the renewal path by NAME, on the same port everything else uses. The endpoint is already served; what has to
# exist is the announcement, because a name nobody announces is a name no agent can send.
#
# A generated deployment used to announce none — so every device it enrolled had no way back, and the only
# remedy was somebody walking to each machine. Measured the hard way: a deployment was replaced underneath a
# real endpoint, and the endpoint could not return. The Edge had been reporting exactly which devices were in
# that state, by name, every ten minutes, into a log nobody reads.
RECOVERY_SNI=""
if [ -n "${DSSE_RECOVERY_SNI:-}" ]; then
  RECOVERY_SNI="-renewal-recovery-sni=$DSSE_RECOVERY_SNI"
fi

# ★★★ AND THE CONSOLE OF EVERY REGION, OR A FAILOVER TAKES THE CONSOLE WITH IT. When a region fails over,
# the Console of the region that took over has to open too.
#
# Every device this deployment steers sends its traffic to an Edge, and an Edge is a forward proxy to the
# public internet: it refuses internal addresses, which is right, and which means an administrator on a
# managed machine cannot open a Console that lives on the customer's network. The profile therefore names the
# Console as a destination the device does not steer — and naming ONE of them is a fix that works until the
# region holding it is the one that failed, which is the moment an administrator needs the Console most.
#
# ★ DERIVED, NOT ASKED FOR, for the same reason -steer-region-failover above is: the operator already declares
# the regions in DSSE_REGION_ENDPOINTS, and a second list is how the two come to disagree — silently, because
# a device that cannot reach the Console looks exactly like a Console that is down. The names come from this
# deployment's own invariant: every plane is a label on one host, so the Console of a region is its agent
# address with the agents. label replaced by console. (dsse-install writes both from planeNamesFor).
#
# ★ A DEPLOYMENT THAT DOES NOT FOLLOW THAT SHAPE SETS ADMIN_CONSOLE_ORIGINS ITSELF, and what it sets is used
# instead of anything derived here. The Edge adds ADMIN_CONSOLE_ORIGIN on its own, so the local region is
# covered either way.
CONSOLE_ORIGINS=""
if [ -n "${ADMIN_CONSOLE_ORIGINS:-}" ]; then
  CONSOLE_ORIGINS="-admin-console-origins=$ADMIN_CONSOLE_ORIGINS"
elif [ -n "${DSSE_REGION_ENDPOINTS:-}" ]; then
  derived="$(printf '%s' "$DSSE_REGION_ENDPOINTS" | tr ';' '\n' \
    | sed -n 's/^[^=]*=//p' | sed 's#//agents\.#//console.#' | tr '\n' ',' | sed 's/,$//')"
  [ -n "$derived" ] && CONSOLE_ORIGINS="-admin-console-origins=$derived"
fi

CONSOLE_ORIGIN=""
if [ -n "${ADMIN_CONSOLE_ORIGIN:-}" ]; then
  CONSOLE_ORIGIN="-admin-console-origin=$ADMIN_CONSOLE_ORIGIN"
fi

FRONT_DOORS=""
if [ -n "${DSSE_TRUSTED_FRONT_DOORS:-}" ]; then
  FRONT_DOORS="-trusted-front-doors=$DSSE_TRUSTED_FRONT_DOORS"
fi

# ★★★ THE DATA-PLANE MESH, WHICH THIS INSTALLER USED TO NAME AND NEVER PRODUCE.
#
# The install order printed by -region lists the mesh as one of the three things done after every region
# exists. Nothing generated a single flag for it, so an operator following that order had no way to do the
# step with what this installer had given them.
#
# The mesh relays a flow that was DECRYPTED HERE to the Edge of the region where the connector lives, and that
# Edge bridges it into its local connector. It never decrypts what it relays, so decryption stays in the region
# that did it — residency holds by construction rather than by rule.
#
# ★ EMPTY IS A DECISION, AND IT IS THE DEFAULT. With no peers there is NO path to a connector in another
# region; a flow that needs one is refused by name ("connector X is in region Y; no mesh link configured from
# this edge") rather than quietly finding some other way out. Set DSSE_MESH_PEERS only when you mean to.
#
#   DSSE_MESH_PEERS='region-b=wss://<the doorway of region-b>/mesh/ingress/tunnel'
#
# ★ IT TURNS ON BOTH HALVES OF THIS REGION'S LINK. A mesh link is mutual: the region that dials also has to be
# dialled. Two separate variables would let a region be configured to reach its peer and not to be reached,
# which looks like a network fault and is a missing line.
#
# ★ AND IT NEEDS NO NEW MATERIAL. The peer's server certificate is pinned to the deployment's own anchor, and
# this Edge proves itself with the identity it already holds. That identity is the FLEET's (CN=dsse-edge-fleet),
# not this node's: every Edge of this deployment is an equally trusted peer of every other, and nothing in the
# mesh distinguishes them. Which is why the allowed-peer set is that one name — it authorises this deployment's
# Edges and nobody else's.
#
# ★★★ THE AUTHORITY THAT PROVES A PEER IS THE MANAGEMENT CA, AND NOT THE ANCHOR (both measured).
# The device-identity tier proves ENDPOINTS AND CONNECTORS and is per-organization, while
# the certificate a deployment presents to name ITSELF is the operator's. A sibling Edge is the second. Naming
# the anchor instead looks equivalent and is not — the management CA and the device CA are siblings beneath it,
# so anchoring there makes every DEVICE chain root at the anchor too and nothing tells an endpoint from the
# deployment. That was measured as a connector holding a certificate this deployment issued and being unable
# to join it.
# ★ AND THE SIBLING IN THIS REGION IS A PEER TOO. See the note beside DSSE_EDGE_SIBLINGS in the compose file:
# a connector can only ever hold a tunnel on ONE node behind a source-hashed door, so the node that does not
# hold it relays to the one that does. It is the same link, keyed by this region's own id, so everything that
# already understands a peer-Edge link understands this one.
if [ -n "${DSSE_EDGE_SIBLINGS:-}" ] && [ -n "${DSSE_EDGE_REGION:-}" ]; then
  if [ -n "${DSSE_MESH_PEERS:-}" ]; then
    DSSE_MESH_PEERS="$DSSE_MESH_PEERS;$DSSE_EDGE_REGION=$DSSE_EDGE_SIBLINGS"
  else
    DSSE_MESH_PEERS="$DSSE_EDGE_REGION=$DSSE_EDGE_SIBLINGS"
  fi
fi
MESH=""
if [ -n "${DSSE_MESH_PEERS:-}" ]; then
  MESH="-mesh-peers=$DSSE_MESH_PEERS"
  MESH="$MESH -mesh-peer-ca=$here/deployment-anchor.pem"
  MESH="$MESH -mesh-client-cert=$here/edge-identity.crt -mesh-client-key=$here/edge-identity.key"
  MESH="$MESH -mesh-peer-identity-ca=$here/management-ca.crt"
  MESH="$MESH -mesh-ingress-allowed-peers=${DSSE_MESH_PEER_IDENTITY:-dsse-edge-fleet}"
fi

# ★★ AND A SECOND GATE, ALSO EMPTY BY DEFAULT. Having a mesh link does not put anything on it: a destination
# reaches another region only if it OPTS IN here. Without this list, a link that is up and healthy relays
# nothing, and a flow whose connector is elsewhere is refused exactly as if there were no link at all. Two
# gates because they answer different questions — "may these regions relay for each other" and "may THIS
# destination leave the region it was decrypted in".
MESH_HOSTS=""
if [ -n "${DSSE_MESH_ELIGIBLE_HOSTS:-}" ]; then
  MESH_HOSTS="-mesh-eligible-hosts=$DSSE_MESH_ELIGIBLE_HOSTS"
fi

# ★★★ THE CONTROL CHANNEL'S WAY OUT OF A DEAD REGION — the multi-region install order's control-plane failover step, also named and never generated
#. Every Edge this installer produced took a SINGLE -config-source-url. When the control planes
# that answer it are gone, that Edge has nowhere else to ask: it keeps serving what it last applied, for ever,
# and nothing it can do brings it back. The deployment has ONE leader wherever the Postgres primary is, so the
# answer is not "another URL" but "the list of places leadership can be, probed".
#
#   DSSE_CP_ENDPOINTS='region-a=https://admin.<A>;region-b=https://admin.<B>'
#   DSSE_CP_HOME=region-a
#
# ★ WHAT IT DOES IS PROBE, NOT GUESS. The Edge asks each entry's GET /leader and pulls from whichever answers
# 200 — the same client-driven selection the device→Edge path uses, and for the same reason: there is no DNS
# in this deployment's routing, so nothing else could move the answer.
#
# ★ AND EMPTY KEEPS TODAY'S BEHAVIOUR EXACTLY. One URL, no probing. A single-region deployment has one place
# leadership can be, and a list of one is the same list.
CP_ENDPOINTS=""
if [ -n "${DSSE_CP_ENDPOINTS:-}" ]; then
  CP_ENDPOINTS="-config-source-endpoints=$DSSE_CP_ENDPOINTS"
  if [ -n "${DSSE_CP_HOME:-}" ]; then
    CP_ENDPOINTS="$CP_ENDPOINTS -config-source-home=$DSSE_CP_HOME"
  fi
  # ★★★ AND THE WRITE ADDRESS OF THE SAME REGIONS (measured). The list above is where a node
  # READS from. What it WRITES — the history it recorded, an enrolment it completed, a connector that joined —
  # goes to the DATA door, which is a different address of the same region. Left as one fixed address, a
  # leadership move stranded every one of those: the outbox held them, so nothing was lost and nothing
  # arrived, for as long as leadership stayed away.
  #
  #   enrolment_report_outbox: delivered=0 still_pending=2   (growing)
  #   the authority counts the connector -> registered on an Edge, and the control plane does not name it
  #
  # Same decision, second address — the region is whichever one the read path selected, because there is one
  # leader.
  if [ -n "${DSSE_CP_DATA_ENDPOINTS:-}" ]; then
    CP_ENDPOINTS="$CP_ENDPOINTS -config-source-data-endpoints=$DSSE_CP_DATA_ENDPOINTS"
  fi
fi

# ★★★ THE THIRD TIER. WITHOUT THIS THE DEPLOYMENT INSPECTS NOTHING (reported from real hardware).
# The architecture names three tiers — transport, device-identity, interception — and this script mentioned the
# first two. The organization checklist then reported "done 4/13, blocking []" on a deployment where no traffic
# had ever been decrypted, because a step nobody can see reads the same as a step that is finished.
#
# ★ THE AUTHORITY IS THE DEPLOYMENT'S, NOT THIS NODE'S. The engine reuses the root material already on disk and
# mints its own only when there is none, so pointing every Edge at the deployment's own interception CA is what
# makes a fleet sign under ONE authority — instead of each node inventing a root that no device has heard of
# and no other node can verify.
#
# ★ AND IT IS DECIDED FROM THE ClientHello. A steer-all agent hands over addresses, not names (Chrome resolves
# for itself), so deciding what to intercept from the address intercepts the wrong things and misses the rest.
INTERCEPT=""
if [ "${DSSE_INTERCEPT:-1}" = "1" ] && [ -f "$here/lantern_dsse_interception_root_ca.pem" ]; then
  INTERCEPT="-network-extension-runtime-copy-lab-tls-interception-hosts=${DSSE_INTERCEPT_HOSTS:-*}"
  INTERCEPT="$INTERCEPT -network-extension-runtime-copy-lab-tls-sni-based-intercept"
  INTERCEPT="$INTERCEPT -network-extension-runtime-copy-lab-tls-root-ca-cert-out=$here/lantern_dsse_interception_root_ca.pem"
  # An adopted re-parent — this deployment's interception authority placed under a customer's or an operator's
  # root — has to survive a restart, or every restart quietly returns to signing under the old one.
  INTERCEPT="$INTERCEPT -interception-reparent-state-dir=${DSSE_EDGE_STATE_DIR:-$here/edge-state}"
  # ★★★ AND AN ORGANIZATION'S OWN INTERCEPTION ROOT HAS TO OUTLIVE THE PROCESS THAT MINTED IT (
  # measured). Without this the registry is in-memory, and "in-memory" on a region with two Edge processes
  # behind one door means something worse than "lost on restart":
  #
  #	osaka-edge-a signs Sakura Foods under  0a8fc598…
  #	the door's trust bundle announces      d5e54171…   (minted by osaka-edge-b)
  #
  # The organization has as many interception roots as there are Edge processes, all different, none written
  # down — and which one signs a device's traffic depends on which process the door happened to pick. A device
  # told to trust one of them fails on the others. Provisioning answered 200 four times on the way there.
  #
  # Beside the re-parent state, because it is the same question: what this Edge signs under must not be
  # re-decided by a restart.
  INTERCEPT="$INTERCEPT -interception-per-tenant-root-dir=${DSSE_EDGE_STATE_DIR:-$here/edge-state}/interception-roots"
  # ★★★ AND WHAT A DEVICE MUST HOLD IS THE ANCHOR, NOT THIS AUTHORITY (letter 112, measured on a
  # real Windows machine). This deployment's interception CA is signed by the deployment root, so it is an
  # INTERMEDIATE: an operator who installed exactly the fingerprint the Edge announced, into the Root store,
  # still lost every HTTPS request on the box with SEC_E_UNTRUSTED_ROOT. The Edge presents this authority in
  # the handshake, so a device holding the deployment's anchor accepts the chain — and the anchor is the only
  # thing worth naming to it.
  INTERCEPT="$INTERCEPT -interception-anchor-cert=$here/deployment-anchor.pem"
elif [ "${DSSE_INTERCEPT:-1}" = "1" ]; then
  echo "start-edge: this deployment has no interception authority on disk" >&2
  echo "  ($here/lantern_dsse_interception_root_ca.pem is missing), so NOTHING WILL BE INSPECTED." >&2
  echo "  A deployment minted without one can be given it: re-run dsse-install against this" >&2
  echo "  directory to add it, or set DSSE_INTERCEPT=0 to say the absence is deliberate." >&2
fi

# ★★★ AND THE ROOT HAS TO REACH THE DEVICES, OR INSPECTING IS AN OUTAGE (reported from real
# hardware as letter 110, hours after the tier above was added). The Edge began decrypting and the enrolled
# Windows machine had never been given the root: bringing steering up killed EVERY outbound TLS connection on
# it — git, the API client, all of it, SEC_E_UNTRUSTED_ROOT — and it had to be taken down again.
#
# ★★ THE POSTURE DOES NOT SAVE IT. That machine was fail-open. Fail-open fires when a flow cannot be CARRIED,
# and this flow was carried perfectly — tunnel healthy, mux pool grown to two. What was missing was trust, so
# nothing looked like a failure to the agent and the posture stayed out of it. fail-closed would have ended
# the same way. Every device of the fleet would go at once, whatever their posture.
#
# ★ THE DEVICE CANNOT SEE THIS COMING. All an agent knows at start-up is how many roots it was handed; whether
# the deployment intends to inspect is known only on this side. So the two are turned on TOGETHER here: the
# signed trust bundle is what names the roots a device must hold, and without it the agent reports
# "interception_root_trust wanted=0" — indistinguishable, from the device, from a deployment that does not
# inspect at all.
#
# Serving it does not by itself put the root in a machine's trust store — that is MDM's job, or an
# administrator's — but it is what lets a device SAY whether it has it (wanted=N found=M), which is the only
# way an operator can see the fleet is ready before the first browser fails.
# ★ THE ANCHOR IS THE ROOT, NOT THE SIGNING INTERMEDIATE. An Edge sends its leaf and the intermediate that
# signed it, so a device anchored on the ROOT can build a chain wherever it runs. Anchored on the intermediate
# it can only do so where a chain may end at a certificate that is not self-signed — which some platforms
# allow and others refuse, so the same publication reaches part of a fleet and freezes the rest, and no log on
# either side says the two disagree. This is also what the install profile hands a device, so the two
# mechanisms tell it one thing instead of two.
TRUST_BUNDLE=""
if [ -f "$here/deployment-anchor.pem" ]; then
  TRUST_BUNDLE="-trust-bundle-ca=$here/deployment-anchor.pem"
elif [ -f "$here/transport-ca.crt" ]; then
  # A deployment generated before the root was written beside the launch script. The intermediate is what it
  # has; devices that can anchor on it keep working and the rest stay where they are, which is the behaviour
  # this file had before.
  TRUST_BUNDLE="-trust-bundle-ca=$here/transport-ca.crt"
else
  echo "start-edge: this deployment has neither $here/deployment-anchor.pem nor $here/transport-ca.crt, so the signed" >&2
  echo "  trust bundle is NOT served and no device can learn which interception root to hold. If this" >&2
  echo "  deployment inspects, every device that arms steering will lose all outbound TLS." >&2
fi
# ★★★ THESE BELONG TO THE BUNDLE, NOT TO ONE WAY OF FINDING IT — so they sit outside the branches that choose
# which anchor to serve. Inside one, the other branch runs without them: the bundle is still served and
# devices still adopt it, so nothing looks wrong, and what has gone is the ability to CHANGE the set. An
# operator adding a certificate is told "the trust set on this node is fixed at startup", which reads like a
# deliberate deployment posture.
#
# ★ BUMP THE SERIAL WHENEVER THE PUBLISHED SET CHANGES. Devices refuse a bundle that does not advance past the
# highest serial they have accepted, which is what stops a replayed older set from narrowing what they trust.
# At 0 — which is what a missing flag gives — nothing can ever advance past it either.
if [ -n "$TRUST_BUNDLE" ]; then
  TRUST_BUNDLE="$TRUST_BUNDLE -trust-bundle-serial=${DSSE_TRUST_BUNDLE_SERIAL:-1}"
  # Runtime-mutable, so an operator can add a certificate and — behind the fleet-coverage gate — withdraw one,
  # with the serial advancing on every change. Without it the published set is whatever this file said at boot.
  TRUST_BUNDLE="$TRUST_BUNDLE -transport-trust-store=${DSSE_EDGE_STATE_DIR:-$here/edge-state}/transport-trust.json"
fi

# ★★★ THE PAID LANE, AND IT IS OFF UNLESS A VENDOR KEY IS ON DISK (the first time it was walked).
#
# The absence of a licence is the ORDINARY state, not a degraded one: the OSS release, every single-organization
# install and the reference lab have no relationship with a vendor and are unlimited. So nothing here is
# defaulted on — with no key file this deployment starts exactly as it did before this block existed, and
# Enforced stays false so the gate is never even constructed.
#
# ★ A LICENCE IS AN ATTESTATION, NOT AN ENFORCEMENT. It may refuse GROWTH — new enrolments past the certified
# scope — and it may never stop steering, cut traffic or disable a feature, because ending a commercial
# relationship must not take a customer's running deployment down. The seat quota does not even refuse growth
# today; it alerts. That boundary is held by ops/checks/no_licence_traffic_gate.sh, not by this comment.
#
# The stores are left to -state-dir, which defaults them: a licence store that is forgotten on restart re-opens
# the replay the signature cannot catch (an older file with more seats on it), and a seat-allocation store that
# is lost reads as zero seats for every tenant.
LICENCE=""
if [ -f "$here/runtime/licence-vendor-keys.pem" ]; then
  LICENCE="-license-vendor-keys=$here/runtime/licence-vendor-keys.pem"
  if [ -n "${DSSE_LICENCE_MSSP_ID:-}" ]; then
    LICENCE="$LICENCE -license-mssp-id=${DSSE_LICENCE_MSSP_ID}"
  else
    # ★ SAY IT RATHER THAN REFUSE. Accepting any addressee is what the flag documents as lab-only, and a
    # deployment that started yesterday must not stop starting because this was added — but an operator who
    # thinks they are licensed to themselves should not find out otherwise from a support case.
    echo "start-edge: a vendor signing key is present but DSSE_LICENCE_MSSP_ID is unset, so a licence issued" >&2
    echo "  to ANY MSSP verifies here. That is the addressee check which makes sign-then-encrypt safe, and" >&2
    echo "  without it a licence minted for somebody else can be applied to this deployment." >&2
  fi
  # Only for licences the vendor SEALED to this deployment. This key protects confidentiality alone: losing it
  # lets somebody read a licence addressed here and does NOT let them mint one, which needs the vendor's
  # signing key — that difference is why this one lives in a file and the vendor's lives in hardware.
  if [ -f "$here/runtime/licence-recipient.key" ]; then
    LICENCE="$LICENCE -license-recipient-key=$here/runtime/licence-recipient.key"
  fi
fi

exec "$DSSE_EDGE_BINARY" \
  $TRUST_BUNDLE $LICENCE \
  -listen="$DSSE_EDGE_LISTEN" -admin-listen="$DSSE_EDGE_ADMIN_LISTEN" \
  -tls-cert="$here/transport.crt" -tls-key="$here/transport.key" \
  -device-ca-cert="$here/device-ca.crt" -device-ca-key="$here/device-ca.key" \
  -policy="$here/policy.json,$here/policy-egress.json" -bundle="$here/policy-bundle.json" \
  -schema-dir="$here/schemas" \
  -operator-tenant-id="${DSSE_OPERATOR_TENANT:-tenant_default}" \
  -agent-policy-signing-key="$here/agent-policy-signing.key" \
  -state-dir="${DSSE_EDGE_STATE_DIR:-$here/edge-state}" \
  -log-dir="${DSSE_EDGE_STATE_DIR:-$here/edge-state}/logs" \
  -transport-tenant-ca-registry="${DSSE_EDGE_STATE_DIR:-$here/edge-state}/device-ca-registry.json" \
  -audit-ingest-url="$DSSE_CONTROL_PLANE_DATA/audit-ingest" \
  -audit-ingest-ca="$here/deployment-anchor.pem" \
  -audit-ingest-client-cert="$here/edge-identity.crt" -audit-ingest-client-key="$here/edge-identity.key" \
  -tenant-transport-material-from-cp \
  -config-source-url="$DSSE_CONTROL_PLANE" \
  -config-source-ca="$here/deployment-anchor.pem" \
  -agent-update-pin="$(cat "$here/agent-update-signing.pub" 2>/dev/null | tr -d '\n')" \
  -agent-update-source-url="$DSSE_CONTROL_PLANE" \
  -agent-update-manifest-dir="${DSSE_EDGE_STATE_DIR:-$here/edge-state}/agent-updates" \
  -agent-rollout-source-url="$DSSE_CONTROL_PLANE" \
  -admin-session-authority-url="$DSSE_CONTROL_PLANE/admin/session" \
  -admin-session-authority-ca="$here/deployment-anchor.pem" \
  $FLEET_TOKEN \
  $REGION $REGION_MAP $REGION_FAILOVER $FRONT_DOORS $RECOVERY_SNI $CONSOLE_ORIGIN $CONSOLE_ORIGINS $MESH $MESH_HOSTS $CP_ENDPOINTS $INTERCEPT $CLIENTLESS \
  -admin-token="$ADMIN_TOKEN" \
  -connector-secret="$CONNECTOR_SECRET" \
  -workload-attestation-secret="$WORKLOAD_SECRET" \
  -step-up-binding-secret="${STEPUP_BINDING_SECRET:-$CONNECTOR_SECRET}" \
  -audit-ingest-token="$AUDIT_INGEST_TOKEN" \
  -connector-runtime-secret-required \
  -workload-attestation-nonce-store=memory -allow-ephemeral-attestation-nonce-store \
  "$@"

# ★★★ AND THE CANONICAL LOG IS ON THE DURABLE VOLUME (measured on the generated deployment).
#
# -log-dir defaults to the RELATIVE path "var/logs", which resolves against the process's working directory —
# inside a container, that is the image's writable layer. The architecture calls this log the canonical one:
# "the local jsonl is the original and the shipment is the copy; if the control plane is down the record is not
# lost". Measured: every jsonl on every Edge and control plane was in /var/logs, which is NOT the mounted
# volume, so every recreate of a container destroyed that deployment's audit history — and the only remaining
# copy was the one at the far end of a best-effort shipment.
#
# This deployment has found the same defect before, in the reference lab. An installer that generates the
# mount and then writes outside it makes the durable volume decorative.
# ★★★ AN EDGE IS A RELYING PARTY, NOT AN AUTHORITY (found by checking it). Without
# -admin-session-authority-url this Edge holds no admin auth of its own and nothing can authenticate to it —
# so its admin surface answers 401 to everything, including to a check asking whether it correctly REFUSES to
# author what the control plane owns. "Refused for authentication" and "refused because the authority is
# elsewhere" are different answers, and only one of them says the deployment is right.
#
# The Edge introspects a session or an API token against the control plane and authorises as a relying party.
# It never mints one: if the control plane is unreachable this Edge refuses ADMINISTRATION and keeps ENFORCING,
# which is the safe direction — whether an operator can log in is not what protects a customer's traffic.
#
# ★★★ -steer-exclusion-source-token IS THIS EDGE'S OWN CREDENTIAL FOR THE CONTROL PLANE, and it is what makes
# the deployment survivable once the break-glass credential is closed. An Edge pulls its configuration over the
# admin surface; before this it authenticated with -admin-token — the break-glass credential, the one that is
# supposed to stop working. So the moment a deployment created its first administrator and restarted, every
# Edge stopped receiving configuration: still healthy, still enforcing what it booted with, and nothing said
# so. Found by closing the circle and running the check.
#
# dsse-install -bootstrap-admin mints a named, read-scoped token for the fleet and writes it into
# deployment.env as EDGE_CP_TOKEN. Until it has run, this is empty and the Edge falls back to -admin-token,
# which is correct: at that point the break-glass credential is the only one there is.
#
# ★ THE DEVICE CA IS ON THIS SCRIPT, NOT ON THE CONTROL PLANE'S. Devices reach an EDGE to enrol, because that
# is where the transport is. What the Edge does NOT do is decide alone: whether a one-time token may be spent,
# and whether an identity has already enrolled, are both asked of the control plane. That is why this script
# has no database of its own — and why the nonce store above is memory with the flag that says out loud it is
# per-instance replay protection only.
#
# ★★★ AN EDGE RECORDS AND THE AUTHORITY KEEPS — AND WITHOUT -audit-ingest-url NOTHING WAS KEPT ANYWHERE
# (found by counting the control plane's durable components against what this installer
# generated). The log path is: an Edge
# writes what it decided, ships it to the control plane, and the control plane owns the hot store and the
# archive. A generated deployment had no ClickHouse, no archive and no shipping URL, so every record died on
# the node that made it and every screen in the Console read an empty store.
#
# ★ SHIPPING IS BEST-EFFORT AND ENFORCEMENT DOES NOT WAIT FOR IT (invariant 7). A control plane that is away
# costs a spool and a retry; it must never cost a decision. The local jsonl stays canonical on the node.
#
# ★★★ THE DEVICE-CA REGISTRY IS THIS EDGE'S CACHE, AND IT HAS TO BE ON DISK (found by restarting).
# Which authorities may have issued a device's certificate is the control plane's answer, carried in the config
# bundle. Without a path the Edge adopts it into memory and says so —
#
#   config_bundle_device_cas_applied_but_not_persisted: no tenant CA registry path is configured,
#   so this registration would be lost on restart
#
# — and it is lost on restart, after which no device of any organization is admitted until the next bundle
# arrives. The window is small and the failure is total, which is the worst combination to debug: a restarted
# Edge that refuses the whole fleet for a minute and then does not.
#
# ★ EVERY EDGE RUNS THIS SAME SCRIPT. They differ in DSSE_EDGE_LISTEN and DSSE_EDGE_STATE_DIR, and in nothing
# else: a fleet is identical nodes with different addresses.
`

	for name, body := range map[string]string{"start-control-plane.sh": cp, "start-edge.sh": edge} {
		// ★ THESE ARE ALWAYS REWRITTEN, AND A REPAIR HAS TO SAY SO (2026-08-31). The launch scripts do not go
		// through keepWhatIsThere — they are derived, and replacing them is the point — but that meant a
		// repair's report listed only the files that DID go through the guard, so the two scripts that carry
		// every flag this deployment runs with were absent from the account of what had just been rewritten.
		// A report that omits what changed is the same problem as one that claims what did not, one sign over.
		changed := true
		if existing, rerr := os.ReadFile(at(name)); rerr == nil && string(existing) == body {
			changed = false
		}
		if err := os.WriteFile(at(name), []byte(body), 0o700); err != nil {
			return fmt.Errorf("write %s: %w", name, err)
		}
		if regeneratingDerivedFiles && changed {
			noteDerivedFile(at(name), "", "")
		}
		// ★★★ AND IT HAS TO PARSE (2026-08-23, found by running one). A single apostrophe inside a
		// ${VAR:?message} opened a quote that never closed, and the generated script died with "unexpected
		// EOF" before it reached a single flag — a deployment that cannot start, produced by the tool whose
		// job is to make it start. Nothing but running it would have shown that, so the installer runs it.
		//
		// sh -n parses without executing, so this cannot start anything or read a secret. A host with no sh
		// is not a failure: the check simply cannot run there, and it says so rather than passing quietly.
		if err := checkShellSyntax(at(name)); err != nil {
			return fmt.Errorf("the generated %s does not parse: %w", name, err)
		}
	}
	return nil
}

// checkShellSyntax parses a generated script without running it.
func checkShellSyntax(path string) error {
	sh, err := exec.LookPath("sh")
	if err != nil {
		fmt.Printf("  note: sh was not found, so %s could not be checked for syntax here.\n", filepath.Base(path))
		return nil
	}
	out, err := exec.Command(sh, "-n", path).CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// launchScriptNames is what report() names, kept beside the scripts so the two cannot drift.
func launchScriptNames() string {
	return strings.Join([]string{"start-control-plane.sh", "start-edge.sh"}, " and ")
}
