import XCTest
@testable import DsseAppProxyProviderSkeleton

// The properties that matter about update reporting, on the side that SENDS.
//
// The reports are written by Go and read here, so the two ends have to agree on the file layout and on what the
// Edge is told. The cases that matter run against a fixture directory GENERATED BY THE GO PRODUCER (see
// goFixtures) — hand-written JSON is kept only for the malformed-input cases, which the producer cannot emit.
final class DsseUpdateReportsTests: XCTestCase {
    private func makeDir() throws -> URL {
        let dir = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("dsse-reports-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    private func write(_ dir: URL, name: String, json: [String: Any]) throws {
        let data = try JSONSerialization.data(withJSONObject: json)
        try data.write(to: dir.appendingPathComponent(name))
    }

    // Oldest first: "failed, then installed" and "installed, then failed" are different stories about the same
    // device, and the file names carry the timestamp so sorting them sorts by when they happened.
    func testPendingReportsAreOrderedOldestFirst() throws {
        let dir = try makeDir()
        try write(dir, name: "20260812T0100Z-a.json", json: ["status": "failed", "at": "2026-08-12T01:00:00Z"])
        try write(dir, name: "20260812T0300Z-c.json", json: ["status": "installed", "at": "2026-08-12T03:00:00Z"])
        try write(dir, name: "20260812T0200Z-b.json", json: ["status": "failed", "at": "2026-08-12T02:00:00Z"])
        // Bookkeeping, not a report.
        try write(dir, name: "dropped.json", json: ["dropped": 3])
        // A partially written file the Go side has not renamed into place yet.
        try write(dir, name: ".report-tmp", json: ["status": "installed", "at": "2026-08-12T04:00:00Z"])

        let names = DsseUpdateReportStore.pending(in: dir).map { $0.lastPathComponent }
        XCTAssertEqual(names, ["20260812T0100Z-a.json", "20260812T0200Z-b.json", "20260812T0300Z-c.json"])
    }

    // ★ A FILE NOTHING CAN READ MUST NOT BLOCK EVERY REPORT BEHIND IT FOREVER. One lost event, said out loud,
    // beats a queue that never drains again because of one bad byte.
    func testAnUnreadableReportIsRemovedRatherThanRetriedForever() throws {
        let dir = try makeDir()
        let bad = dir.appendingPathComponent("20260812T0100Z-bad.json")
        try Data("{not json".utf8).write(to: bad)

        XCTAssertNil(DsseUpdateReportStore.read(bad))
        XCTAssertFalse(FileManager.default.fileExists(atPath: bad.path))
    }

    // A report with no status, or no timestamp, cannot be ordered or interpreted and is treated the same way.
    func testAReportMissingItsStatusOrTimestampIsRejected() throws {
        let dir = try makeDir()
        let noStatus = dir.appendingPathComponent("20260812T0100Z-x.json")
        try write(dir, name: "20260812T0100Z-x.json", json: ["at": "2026-08-12T01:00:00Z"])
        XCTAssertNil(DsseUpdateReportStore.read(noStatus))

        let noTime = dir.appendingPathComponent("20260812T0200Z-y.json")
        try write(dir, name: "20260812T0200Z-y.json", json: ["status": "installed"])
        XCTAssertNil(DsseUpdateReportStore.read(noTime))
    }

    // ★ THE IDENTITY IN THE BODY IS THE SENDER'S, NOT THE REPORT'S. The updater records what it could read
    // locally; the authoritative answer is the certificate the Edge checked. A device that mis-identifies
    // itself in a fleet report is worse than one that does not report.
    func testTheBodyCarriesTheSendersIdentityNotTheReports() throws {
        let dir = try makeDir()
        try write(dir, name: "20260812T0100Z-a.json", json: [
            "status": "installed", "at": "2026-08-12T01:00:00Z",
            "target_version": "0.2.7", "running_version": "0.2.7+20260811211900",
            "from_version": "0.2.4", "kind": "update",
            "device_id": "whatever-the-updater-read", "tenant_id": "some-other-tenant",
        ])
        let report = try XCTUnwrap(DsseUpdateReportStore.read(dir.appendingPathComponent("20260812T0100Z-a.json")))
        let body = DsseUpdateReportStore.body(for: report, deviceID: "mac-dev-1", tenantID: "tenant_a")

        XCTAssertEqual(body["device_id"] as? String, "mac-dev-1")
        XCTAssertEqual(body["tenant_id"] as? String, "tenant_a")
        XCTAssertEqual(body["update_status"] as? String, "installed")
        XCTAssertEqual(body["target_agent_version"] as? String, "0.2.7")
        XCTAssertEqual(body["current_agent_version"] as? String, "0.2.7+20260811211900")
        // control_plane, not "dsse": the Edge CHECKs update_source IN ('mdm','control_plane','manual').
        XCTAssertEqual(body["update_source"] as? String, "control_plane")
        let meta = try XCTUnwrap(body["metadata"] as? [String: Any])
        XCTAssertEqual(meta["from_version"] as? String, "0.2.4")
        XCTAssertEqual(meta["reported_by"] as? String, "dsse-network-extension")
    }

    // ★ A ROLLBACK AND AN UPDATE MUST NOT READ THE SAME — and rolled_back goes out AS ITSELF. This test used
    // to assert it was flattened to `installed`; the Edge counts rolled_back SEPARATELY, so flattening counted
    // every rollback as a successful update and inflated the rollout success rate with the events that most
    // contradict it.
    func testARollbackIsDistinguishableInTheBody() throws {
        let dir = try makeDir()
        try write(dir, name: "20260812T0100Z-r.json", json: [
            "status": "rolled_back", "at": "2026-08-12T01:00:00Z",
            "target_version": "0.2.4", "from_version": "0.2.5", "kind": "rollback",
        ])
        let report = try XCTUnwrap(DsseUpdateReportStore.read(dir.appendingPathComponent("20260812T0100Z-r.json")))
        let body = DsseUpdateReportStore.body(for: report, deviceID: "mac-dev-1", tenantID: "tenant_a")

        XCTAssertEqual(body["update_status"] as? String, "rolled_back")
        let meta = try XCTUnwrap(body["metadata"] as? [String: Any])
        XCTAssertEqual(meta["rolled_back"] as? Bool, true)
        XCTAssertEqual(meta["kind"] as? String, "rollback")
        XCTAssertEqual(meta["from_version"] as? String, "0.2.5")
        XCTAssertEqual(body["target_agent_version"] as? String, "0.2.4")
    }

    // ★ THE FIXTURES ARE WRITTEN BY THE GO PRODUCER (2026-08-12, sixth review). These tests used to hand-write
    // the JSON they then asserted on — including a `dropped_before` field that the real producer does not put
    // inside a report at all, so macOS never told the Edge about discarded outcomes and the test could not see
    // it. The fixture directory is generated by agentupdate.AppendReport itself.
    private func goFixtures() throws -> URL {
        let here = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        let dir = here.appendingPathComponent("fixtures/go-reports")
        guard FileManager.default.fileExists(atPath: dir.path) else {
            throw XCTSkip("the Go-produced fixture directory is missing")
        }
        // Copied, because a drain deletes what it sends.
        let work = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("dsse-go-reports-\(UUID().uuidString)")
        try FileManager.default.copyItem(at: dir, to: work)
        return work
    }

    func testGoProducedReportsAreReadableAndOrdered() throws {
        let dir = try goFixtures()
        let reports = DsseUpdateReportStore.pending(in: dir).compactMap { DsseUpdateReportStore.read($0) }
        XCTAssertEqual(reports.count, 3, "the Go producer's files were not all readable here")
        XCTAssertEqual(reports.map(\.status), ["installed", "rolled_back", "refused"])
        // Every one carries an id — without it a retry becomes a new event at the Edge.
        XCTAssertFalse(reports.contains { $0.id.isEmpty })
        // And from_version comes from the journal, not from a test's imagination.
        XCTAssertEqual(reports[0].fromVersion, "0.2.4")
        XCTAssertEqual(reports[1].fromVersion, "0.2.5")
    }

    // ★ THE DROP COUNT LIVES IN A SEPARATE LEDGER, because the reports it counts are exactly the ones that are
    // gone. Swift used to filter that file out and expect the number inside a report.
    func testTheGoLedgerOfDroppedReportsIsRead() throws {
        let dir = try goFixtures()
        XCTAssertEqual(DsseUpdateReportStore.droppedCount(in: dir), 6)

        let report = try XCTUnwrap(DsseUpdateReportStore.read(DsseUpdateReportStore.pending(in: dir)[0]))
        let meta = try XCTUnwrap(DsseUpdateReportStore
            .body(for: report, deviceID: "d", tenantID: "t",
                  droppedBefore: DsseUpdateReportStore.droppedCount(in: dir))["metadata"] as? [String: Any])
        XCTAssertEqual(meta["dropped_before"] as? Int, 6)

        // ★ CLAIMED BY RENAME, NOT DELETED. The sender reads the count, spends a network round trip, and the
        // Go updater may record more drops in between — deleting the whole file at the end would erase them.
        let (claimed, claim) = DsseUpdateReportStore.claimDropped(in: dir)
        XCTAssertEqual(claimed, 6)
        XCTAssertEqual(DsseUpdateReportStore.droppedCount(in: dir), 0, "the ledger was not claimed")

        // A drop recorded WHILE the claim is in flight starts a new ledger and survives the delivery.
        let more = try JSONSerialization.data(withJSONObject: ["dropped": 3])
        try more.write(to: dir.appendingPathComponent("dropped.json"))
        DsseUpdateReportStore.releaseDropped(claim, delivered: true, in: dir)
        XCTAssertEqual(DsseUpdateReportStore.droppedCount(in: dir), 3,
                       "drops recorded during delivery were erased by it")
    }

    // And a claim that was NOT delivered goes back, added to whatever accumulated since.
    func testAnUndeliveredDropClaimIsRestored() throws {
        let dir = try goFixtures()
        let (claimed, claim) = DsseUpdateReportStore.claimDropped(in: dir)
        XCTAssertEqual(claimed, 6)
        let more = try JSONSerialization.data(withJSONObject: ["dropped": 2])
        try more.write(to: dir.appendingPathComponent("dropped.json"))

        DsseUpdateReportStore.releaseDropped(claim, delivered: false, in: dir)
        XCTAssertEqual(DsseUpdateReportStore.droppedCount(in: dir), 8,
                       "an undelivered claim was swallowed instead of being added back")
    }

    // ★ THE EDGE'S SCHEMA IS A CHECK CONSTRAINT. update_source must be one of mdm|control_plane|manual, and a
    // refusal has no status of its own — sending "dsse" or "refused" would be rejected at insert, leaving the
    // fleet view empty for a reason nobody would connect to the sender.
    func testTheBodyUsesValuesTheEdgeSchemaAccepts() throws {
        let dir = try goFixtures()
        for url in DsseUpdateReportStore.pending(in: dir) {
            let report = try XCTUnwrap(DsseUpdateReportStore.read(url))
            let body = DsseUpdateReportStore.body(for: report, deviceID: "d", tenantID: "t")
            XCTAssertEqual(body["update_source"] as? String, "control_plane")
            let status = try XCTUnwrap(body["update_status"] as? String)
            XCTAssertTrue(["available", "downloaded", "installing", "installed", "failed", "rolled_back"]
                .contains(status), "\(status) is not a value the Edge's CHECK constraint accepts")
            if report.status == "refused" {
                let meta = try XCTUnwrap(body["metadata"] as? [String: Any])
                XCTAssertEqual(meta["refused"] as? Bool, true, "a refusal became indistinguishable from a failure")
            }
            if report.status == "rolled_back" {
                // NOT flattened to installed: the Edge counts rolled_back separately, and flattening it counts
                // every rollback as a successful update.
                XCTAssertEqual(status, "rolled_back")
            }
        }
    }

    // A device with no identity cannot address the route, and must not build a URL that would report as
    // somebody else.
    func testNoDeviceIdentityMeansNoURL() {
        XCTAssertNil(DsseUpdateReportStore.url(security: "edge.example.test", port: 8443, deviceID: ""))
        XCTAssertEqual(
            DsseUpdateReportStore.url(security: "edge.example.test", port: 8443, deviceID: "mac dev 1")?.absoluteString,
            "https://edge.example.test:8443/devices/mac%20dev%201/agent-updates")
    }
}
