import {readFileSync} from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import test from 'node:test';
const source=readFileSync(new URL('./dlpfindings.js',import.meta.url),'utf8');
const body=()=>({schema_version:'admin_dlp_findings.v1',tenant_id:'own',no_secret_attestation:true,findings:[{id:'event-1',timestamp:'2026-09-16T00:00:00Z',action:'observe',identifier_types:['email','credit_card'],destination:'sample.example.test',rule_id:'policy-1'}],summary:{total:1,returned:1,blocked:0,by_identifier:{email:1,credit_card:1},by_action:{observe:1},by_destination:{'sample.example.test':1}}});
const response=value=>({ok:true,status:200,body:value});
function fixture(){
 const states=[],tables=[],buttons=[],requests=[],versions=new WeakMap();
 const el=(tag,props={},children=[])=>{const n={tag,props,children:[],isConnected:true,appendChild(x){this.children.push(x)}};Object.defineProperty(n,'innerHTML',{set(){this.children=[]}});n.children=Array.isArray(children)?children:[children];if(tag==='button')buttons.push(n);return n;};
 const ctx=vm.createContext({el,bl:x=>x.en,operateTenant:'',uiBadge:(text,kind)=>({text,kind}),emptyBox:text=>({text}),uiState:(n,state,message,retry)=>{n.innerHTML='';states.push({state,message,retry})},simpleTable:(headers,rows)=>{tables.push({headers,rows});return{headers,rows}},freshRender:n=>{const v=(versions.get(n)||0)+1;versions.set(n,v);return()=>versions.get(n)===v},window:{dsseFormatTime:s=>s},apiFetch:async(method,path)=>{requests.push({method,path});if(path==='/admin/tenant')return response({tenant_id:'own'});if(path==='/admin/dlp-policies')return response({policies:[{id:'policy-1',tenant_id:'own',name:'Protect uploads'}]});return response(body());}});
 vm.runInContext(source,ctx);return{ctx,states,tables,buttons,requests,content:el('div'),el};
}
for(const [name,change] of Object.entries({missing:()=>({}),null:()=>null,collection:v=>(v.findings={},v),nullCollection:v=>(v.findings=null,v),row:v=>(v.findings=[null],v),foreign:v=>(v.tenant_id='other',v),schema:v=>(v.schema_version='unexpected',v),attestation:v=>(v.no_secret_attestation=false,v),summary:v=>(v.summary=null,v),total:v=>(v.summary.total=-1,v),returned:v=>(v.summary.returned=0,v),blocked:v=>(v.summary.blocked=2,v),map:v=>(v.summary.by_identifier.email='1',v),identifier:v=>(v.findings[0].identifier_types='email',v),timestamp:v=>(v.findings[0].timestamp='invalid',v),field:v=>(v.findings[0].source_app={},v),duplicate:v=>(v.findings.push({...v.findings[0]}),v.summary.total=2,v.summary.returned=2,v)})){
 test(`invalid ${name} is an error with retry, never an empty success`,async()=>{const f=fixture(),normal=f.ctx.apiFetch;f.ctx.apiFetch=async(m,path)=>path.startsWith('/admin/dlp-findings')?response(change(body())):normal(m,path);await f.ctx.renderDLPFindingsView(f.content);assert.equal(f.states.at(-1).state,'error');assert.equal(f.states.at(-1).retry.label,'Retry');assert.equal(f.tables.length,0);});
}
test('counts events once across identifiers and permits explicit empty results',async()=>{const f=fixture();await f.ctx.renderDLPFindingsView(f.content);assert.equal(f.tables.length,1);const section=f.content.children[1];assert.equal(section.children[0].children[0].props.text,'1 events · 0 blocked · Showing 1 · ');const empty=body();empty.findings=[];empty.summary={total:0,returned:0,blocked:0,by_identifier:{},by_action:{},by_destination:{}};assert.equal(f.ctx.dlpFindingsBody(response(empty),'own').findings.length,0);assert.ok(f.requests.every(r=>r.method==='GET'));});
test('store failure retry reloads real results',async()=>{const f=fixture(),normal=f.ctx.apiFetch;f.ctx.apiFetch=async(m,p)=>p.startsWith('/admin/dlp-findings')?{ok:false,status:503}:normal(m,p);await f.ctx.renderDLPFindingsView(f.content);assert.equal(f.states.at(-1).state,'error');f.ctx.apiFetch=normal;await f.states.at(-1).retry.onClick();assert.equal(f.tables.length,1);});
test('delayed filter answer cannot overwrite the newer filter',async()=>{const f=fixture(),normal=f.ctx.apiFetch;await f.ctx.renderDLPFindingsView(f.content);let release;f.ctx.apiFetch=(m,p)=>p.includes('identifier=email')?new Promise(r=>release=r):normal(m,p);f.buttons.find(b=>b.props.text==='email (1)').props.onClick();f.buttons.find(b=>b.props.text==='All').props.onClick();await new Promise(setImmediate);const tables=f.tables.length;release(response(body()));await new Promise(setImmediate);assert.equal(f.tables.length,tables);});
test('organization change during policy-name read refuses stale rows',async()=>{const f=fixture(),normal=f.ctx.apiFetch;let release;f.ctx.apiFetch=(m,p)=>p==='/admin/dlp-policies'?new Promise(r=>release=r):normal(m,p);const pending=f.ctx.renderDLPFindingsView(f.content);await new Promise(setImmediate);f.ctx.operateTenant='other';release(response({policies:[]}));await pending;assert.equal(f.tables.length,0);assert.equal(f.states.at(-1).state,'error');});
test('a replaced or disconnected view ignores late results',async()=>{for(const disconnect of [true,false]){const f=fixture(),normal=f.ctx.apiFetch;let release;f.ctx.apiFetch=(m,p)=>p.startsWith('/admin/dlp-findings')?new Promise(r=>release=r):normal(m,p);const pending=f.ctx.renderDLPFindingsView(f.content);if(disconnect)f.content.isConnected=false;else f.ctx.freshRender(f.content);release(response(body()));await pending;assert.equal(f.tables.length,0);assert.deepEqual(f.states.map(s=>s.state),['loading']);}});
test('foreign or unavailable policy name falls back to the recorded id',async()=>{for(const result of [{ok:false,status:503},response({policies:[{id:'policy-1',tenant_id:'other',name:'FOREIGN NAME'}]})]){const f=fixture(),normal=f.ctx.apiFetch;f.ctx.apiFetch=async(m,p)=>p==='/admin/dlp-policies'?result:normal(m,p);await f.ctx.renderDLPFindingsView(f.content);assert.equal(f.tables[0].rows[0][2].children[1].props.text,'policy: policy-1');}});
