import {readFileSync} from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import test from 'node:test';
const source=readFileSync(new URL('./pinned.js',import.meta.url),'utf8');
function fixture(result={ok:true,status:200,body:{}}){const requests=[],alerts=[],confirms=[];let refreshed=0,allow=true;const container={_reloadAll:async()=>{refreshed++}};const context=vm.createContext({bl:o=>o.en,window:{confirm:m=>{confirms.push(m);return allow},alert:m=>alerts.push(m)},apiFetch:async(method,path,body)=>{requests.push({method,path,body});if(result instanceof Error)throw result;return result}});vm.runInContext(source,context);container._write=(path,body)=>context.apiFetch("POST",path,body);return{context,container,requests,alerts,confirms,get refreshed(){return refreshed},cancel(){allow=false}}}
for(const op of ['review','materialize']){
 const invoke=f=>op==='review'?f.context.reviewPinned('id','rejected',f.container):f.context.materializePinned('id',f.container,false,'named.example');
 test(`${op} refreshes both candidate and serving Edge state on success`,async()=>{const f=fixture();await invoke(f);assert.equal(f.requests.length,1);assert.equal(f.refreshed,1);assert.equal(f.alerts.length,0)});
 test(`${op} partial failure remains incomplete and refreshes saved stages`,async()=>{const f=fixture({ok:false,status:500,body:{partial:true,error:'Removal could not be confirmed; the bypass may remain active.'}});await invoke(f);assert.equal(f.requests.length,1);assert.equal(f.refreshed,1);assert.match(f.alerts[0],/^Incomplete: HTTP 500/);assert.match(f.alerts[0],/bypass may remain active/)});
 test(`${op} network failure is visible without a success refresh`,async()=>{const f=fixture(new Error('connection reset'));await invoke(f);assert.equal(f.refreshed,0);assert.match(f.alerts[0],/Could not confirm/);assert.equal(f.requests.length,1)});
 test(`${op} cancellation makes no write`,async()=>{const f=fixture();f.cancel();await invoke(f);assert.equal(f.requests.length,0);assert.equal(f.refreshed,0)});
}
test('high risk adoption retains the second confirmation and explicit body flag',async()=>{const f=fixture();await f.context.materializePinned('id',f.container,true,'named.example');assert.equal(f.confirms.length,2);assert.equal(f.requests[0].body.allow_high_risk,true);assert.equal(f.requests[0].path,'/admin/cert-pin-bypass')});
test('ordinary failure does not claim a partially saved operation',async()=>{const f=fixture({ok:false,status:400,body:{error:'Invalid request'}});await f.context.reviewPinned('id','approved',f.container);assert.match(f.alerts[0],/^Failed: HTTP 400/);assert.equal(f.refreshed,0)});
