import {readFileSync} from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import test from 'node:test';
const source=readFileSync(new URL('./pinned.js',import.meta.url),'utf8');const ok=body=>({ok:true,status:200,body});
const candidate=()=>({tenant_id:'own',candidate_id:'observed',source:'cert_pinning_detection',candidate_type:'bypass_policy',status:'approved',host:'named.example',port:443});
const list=()=>({tenant_id:'own',candidates:[candidate()],count:1,limit:100});
function fixture(){const states=[],paints=[],requests=[],versions=new WeakMap();const node=()=>({isConnected:true,innerHTML:'',querySelectorAll:()=>[]});const content=node(),cs=node(),bs=node(),input={},button={};const ctx=vm.createContext({bl:o=>o.en,operateTenant:'',freshRender:n=>{const v=(versions.get(n)||0)+1;versions.set(n,v);return()=>versions.get(n)===v},uiState:(n,state,message,retry)=>states.push({state,message,retry}),apiFetch:async(method,path,body)=>{requests.push({method,path,body});if(method==='POST')return ok({...candidate(),status:'materialized',candidate_id:'manual'});if(path==='/admin/tenant')return ok({tenant_id:'own'});return ok(path.includes('/policy-candidates')?list():{tenant_id:'own',hosts:null})}});vm.runInContext(source,ctx);ctx.paintPinned=n=>paints.push(n._pinnedAll);ctx.paintBypass=()=>{};const view=ctx.pinnedView(content,cs,bs,input,button,()=> '');return{ctx,view,content,cs,bs,input,button,states,paints,requests};}
for(const [name,mutate]of Object.entries({missing:()=>({}),null:()=>null,foreign:x=>({...x,tenant_id:'other'}),rows:x=>({...x,candidates:null}),row:x=>({...x,candidates:[null]}),wrongOwner:x=>({...x,candidates:[{...candidate(),tenant_id:'other'}]}),duplicate:x=>({...x,count:2,candidates:[candidate(),candidate()]}),status:x=>({...x,candidates:[{...candidate(),status:'bad'}]}),host:x=>({...x,candidates:[{...candidate(),host:4}]}),count:x=>({...x,count:0}),limit:x=>({...x,limit:0}),failureCount:x=>({...x,candidates:[{...candidate(),failure_count:-1}]})}))test(`rejects ${name} candidate response and discards previous actions`,async()=>{const f=fixture();await f.view.load();const normal=f.ctx.apiFetch;f.ctx.apiFetch=(m,p,b)=>p.includes('/policy-candidates')?ok(mutate(list())):normal(m,p,b);await f.view.load();assert.equal(f.states.at(-1).state,'error');assert.equal(f.cs._pinnedAll,undefined);assert.equal(f.button.disabled,true);const count=f.paints.length;f.view.paint();assert.equal(f.paints.length,count);await assert.rejects(f.view.write('/admin/cert-pin-bypass',{host:'named.example'},()=>true));assert.equal(f.requests.filter(r=>r.method==='POST').length,0)});
for(const body of [{},{tenant_id:'other',hosts:[]},{tenant_id:'own',hosts:{}},{tenant_id:'own',hosts:['']}])test('invalid bypass response cannot become none configured',async()=>{const f=fixture(),normal=f.ctx.apiFetch;f.ctx.apiFetch=(m,p,b)=>p.includes('bypass-hosts')?ok(body):normal(m,p,b);await f.view.load();assert.equal(f.states.at(-1).state,'error');assert.equal(f.bs._bypassHosts,undefined)});
test('explicit empty and null hosts are accepted; unrelated bypass candidates are not pinned',async()=>{const f=fixture();const v=list();v.candidates=[{...candidate(),source:'imported'}];assert.equal(f.ctx.pinnedLists(ok(v),ok({tenant_id:'own',hosts:null}),'own').candidates.length,0);v.candidates=[];v.count=0;assert.equal(f.ctx.pinnedLists(ok(v),ok({tenant_id:'own',hosts:[]}),'own').hosts.length,0)});
test('old reload response cannot replace newer data',async()=>{const f=fixture(),normal=f.ctx.apiFetch;let release,first=true;f.ctx.apiFetch=(m,p,b)=>p.includes('policy-candidates')&&first?(first=false,new Promise(r=>release=r)):normal(m,p,b);const pending=f.view.load();await new Promise(setImmediate);await f.view.load();const n=f.paints.length;release(ok({}));await pending;assert.equal(f.paints.length,n);assert.equal(f.button.disabled,false)});
for(const kind of ['selection','replacement','disconnect'])test(`${kind} rejects a late read`,async()=>{const f=fixture(),normal=f.ctx.apiFetch;let release;f.ctx.apiFetch=(m,p,b)=>p.includes('policy-candidates')?new Promise(r=>release=r):normal(m,p,b);const pending=f.view.load();await new Promise(setImmediate);if(kind==='selection')f.ctx.operateTenant='other';if(kind==='replacement')f.ctx.freshRender(f.content);if(kind==='disconnect')f.content.isConnected=false;release(ok(list()));await pending;assert.equal(f.paints.length,0);assert.equal(f.cs._pinnedAll,undefined)});
for(const body of [{},{...candidate(),tenant_id:'other'},{...candidate(),host:'wrong.example',status:'materialized'},{...candidate(),status:'approved'}])test('unmatched write acknowledgement requires reload',async()=>{const f=fixture();await f.view.load();const normal=f.ctx.apiFetch;f.ctx.apiFetch=(m,p,b)=>m==='POST'?ok(body):normal(m,p,b);await assert.rejects(f.view.write('/admin/cert-pin-bypass',{host:'named.example'},c=>f.ctx.pinnedRegistrationMatches(c,'named.example')),/Could not confirm/);assert.equal(f.button.disabled,true);assert.equal(f.cs._pinnedAll,undefined)});
test('write carries tenant precondition, confirms normalized registration and refreshes before next action',async()=>{const f=fixture();await f.view.load();const r=await f.view.write('/admin/cert-pin-bypass',{host:'NAMED.EXAMPLE.'},c=>f.ctx.pinnedRegistrationMatches(c,'NAMED.EXAMPLE.'));assert.equal(r.status,200);assert.equal(f.requests.at(-1).path,'/admin/cert-pin-bypass?expected_tenant_id=own');assert.equal(f.button.disabled,true);await f.view.load();assert.equal(f.button.disabled,false)});
test('changed or unavailable preflight sends no mutation',async()=>{for(const r of [ok({tenant_id:'other'}),{ok:false,status:503},ok({})]){const f=fixture();await f.view.load();const normal=f.ctx.apiFetch;f.ctx.apiFetch=(m,p,b)=>p==='/admin/tenant'?r:normal(m,p,b);await assert.rejects(f.view.write('/admin/cert-pin-bypass',{},()=>true));assert.equal(f.requests.filter(r=>r.method==='POST').length,0);assert.equal(f.button.disabled,true)}});
test('pending write locks all entry points and network failure leaves input',async()=>{const f=fixture();await f.view.load();f.input.value='named.example';const normal=f.ctx.apiFetch;let reject;f.ctx.apiFetch=(m,p,b)=>m==='POST'?new Promise((_,r)=>reject=r):normal(m,p,b);const first=f.view.write('/admin/cert-pin-bypass',{},()=>true);await new Promise(setImmediate);assert.equal(f.button.disabled,true);await assert.rejects(f.view.write('/admin/cert-pin-bypass',{},()=>true));const n=f.requests.length;await f.view.load();assert.equal(f.requests.length,n);reject(new Error('reset'));await assert.rejects(first,/Could not confirm/);assert.equal(f.input.value,'named.example');assert.equal(f.button.disabled,true)});
